// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :exec
INSERT INTO sk_activity (
    activity_no, activity_name,
    start_time, end_time,
    effective_type, effective_days, effective_start, effective_end,
    activity_status, purchase_limit, remark
) VALUES (
    $1, $2,
    $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11
)
`

type CreateActivityParams struct {
	ActivityNo     string      `json:"activity_no"`
	ActivityName   string      `json:"activity_name"`
	StartTime      time.Time   `json:"start_time"`
	EndTime        time.Time   `json:"end_time"`
	EffectiveType  int16       `json:"effective_type"`
	EffectiveDays  pgtype.Text `json:"effective_days"`
	EffectiveStart pgtype.Text `json:"effective_start"`
	EffectiveEnd   pgtype.Text `json:"effective_end"`
	ActivityStatus int16       `json:"activity_status"`
	PurchaseLimit  int32       `json:"purchase_limit"`
	Remark         pgtype.Text `json:"remark"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) error {
	_, err := q.db.Exec(ctx, createActivity,
		arg.ActivityNo,
		arg.ActivityName,
		arg.StartTime,
		arg.EndTime,
		arg.EffectiveType,
		arg.EffectiveDays,
		arg.EffectiveStart,
		arg.EffectiveEnd,
		arg.ActivityStatus,
		arg.PurchaseLimit,
		arg.Remark,
	)
	return err
}

const createProduct = `-- name: CreateProduct :exec

INSERT INTO sk_activity_product (
    activity_no, product_name, product_image,
    original_price, discount_type, discount_price, sort_order
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type CreateProductParams struct {
	ActivityNo    string      `json:"activity_no"`
	ProductName   string      `json:"product_name"`
	ProductImage  pgtype.Text `json:"product_image"`
	OriginalPrice int64       `json:"original_price"`
	DiscountType  int16       `json:"discount_type"`
	DiscountPrice pgtype.Int8 `json:"discount_price"`
	SortOrder     int32       `json:"sort_order"`
}

// ------------------------------------------------------------------
// Product queries
// ------------------------------------------------------------------
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.Exec(ctx, createProduct,
		arg.ActivityNo,
		arg.ProductName,
		arg.ProductImage,
		arg.OriginalPrice,
		arg.DiscountType,
		arg.DiscountPrice,
		arg.SortOrder,
	)
	return err
}

const createRuntimeProduct = `-- name: CreateRuntimeProduct :exec

INSERT INTO sk_product (
    activity_no, product_name, product_image, sku_no,
    original_price, seckill_price,
    total_stock, available_stock, limit_quantity
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9
)
`

type CreateRuntimeProductParams struct {
	ActivityNo     string      `json:"activity_no"`
	ProductName    string      `json:"product_name"`
	ProductImage   pgtype.Text `json:"product_image"`
	SkuNo          string      `json:"sku_no"`
	OriginalPrice  int64       `json:"original_price"`
	SeckillPrice   int64       `json:"seckill_price"`
	TotalStock     int32       `json:"total_stock"`
	AvailableStock int32       `json:"available_stock"`
	LimitQuantity  int32       `json:"limit_quantity"`
}

// ------------------------------------------------------------------
// Runtime product queries
// ------------------------------------------------------------------
func (q *Queries) CreateRuntimeProduct(ctx context.Context, arg CreateRuntimeProductParams) error {
	_, err := q.db.Exec(ctx, createRuntimeProduct,
		arg.ActivityNo,
		arg.ProductName,
		arg.ProductImage,
		arg.SkuNo,
		arg.OriginalPrice,
		arg.SeckillPrice,
		arg.TotalStock,
		arg.AvailableStock,
		arg.LimitQuantity,
	)
	return err
}

const createSKU = `-- name: CreateSKU :exec

INSERT INTO sk_activity_product_sku (
    activity_no, product_id, sku_no,
    activity_stock, discount_type, discount_percent, discount_price
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
`

type CreateSKUParams struct {
	ActivityNo      string      `json:"activity_no"`
	ProductID       int64       `json:"product_id"`
	SkuNo           string      `json:"sku_no"`
	ActivityStock   int32       `json:"activity_stock"`
	DiscountType    int16       `json:"discount_type"`
	DiscountPercent pgtype.Int4 `json:"discount_percent"`
	DiscountPrice   pgtype.Int8 `json:"discount_price"`
}

// ------------------------------------------------------------------
// SKU queries
// ------------------------------------------------------------------
func (q *Queries) CreateSKU(ctx context.Context, arg CreateSKUParams) error {
	_, err := q.db.Exec(ctx, createSKU,
		arg.ActivityNo,
		arg.ProductID,
		arg.SkuNo,
		arg.ActivityStock,
		arg.DiscountType,
		arg.DiscountPercent,
		arg.DiscountPrice,
	)
	return err
}

const getActivity = `-- name: GetActivity :one
SELECT id, activity_no, activity_name, start_time, end_time, effective_type, effective_days, effective_start, effective_end, activity_status, purchase_limit, remark, created_at, updated_at, is_deleted
FROM sk_activity
WHERE activity_no = $1
  AND is_deleted = 0
`

func (q *Queries) GetActivity(ctx context.Context, activityNo string) (SkActivity, error) {
	row := q.db.QueryRow(ctx, getActivity, activityNo)
	var i SkActivity
	err := row.Scan(
		&i.ID,
		&i.ActivityNo,
		&i.ActivityName,
		&i.StartTime,
		&i.EndTime,
		&i.EffectiveType,
		&i.EffectiveDays,
		&i.EffectiveStart,
		&i.EffectiveEnd,
		&i.ActivityStatus,
		&i.PurchaseLimit,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getRuntimeProduct = `-- name: GetRuntimeProduct :one
SELECT id, activity_no, product_name, product_image, sku_no, original_price, seckill_price, total_stock, available_stock, limit_quantity, created_at, updated_at, is_deleted
FROM sk_product
WHERE sku_no = $1
  AND is_deleted = 0
`

func (q *Queries) GetRuntimeProduct(ctx context.Context, skuNo string) (SkProduct, error) {
	row := q.db.QueryRow(ctx, getRuntimeProduct, skuNo)
	var i SkProduct
	err := row.Scan(
		&i.ID,
		&i.ActivityNo,
		&i.ProductName,
		&i.ProductImage,
		&i.SkuNo,
		&i.OriginalPrice,
		&i.SeckillPrice,
		&i.TotalStock,
		&i.AvailableStock,
		&i.LimitQuantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getSKU = `-- name: GetSKU :one
SELECT id, activity_no, product_id, sku_no, activity_stock, discount_type, discount_percent, discount_price, created_at, updated_at, is_deleted
FROM sk_activity_product_sku
WHERE sku_no = $1
  AND is_deleted = 0
`

func (q *Queries) GetSKU(ctx context.Context, skuNo string) (SkActivityProductSku, error) {
	row := q.db.QueryRow(ctx, getSKU, skuNo)
	var i SkActivityProductSku
	err := row.Scan(
		&i.ID,
		&i.ActivityNo,
		&i.ProductID,
		&i.SkuNo,
		&i.ActivityStock,
		&i.DiscountType,
		&i.DiscountPercent,
		&i.DiscountPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, activity_no, activity_name, start_time, end_time, effective_type, effective_days, effective_start, effective_end, activity_status, purchase_limit, remark, created_at, updated_at, is_deleted
FROM sk_activity
WHERE ($3 IS NULL OR activity_status = $3)
  AND is_deleted = 0
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActivitiesParams struct {
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	ActivityStatus interface{} `json:"activity_status"`
}

func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]SkActivity, error) {
	rows, err := q.db.Query(ctx, listActivities, arg.Limit, arg.Offset, arg.ActivityStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkActivity{}
	for rows.Next() {
		var i SkActivity
		if err := rows.Scan(
			&i.ID,
			&i.ActivityNo,
			&i.ActivityName,
			&i.StartTime,
			&i.EndTime,
			&i.EffectiveType,
			&i.EffectiveDays,
			&i.EffectiveStart,
			&i.EffectiveEnd,
			&i.ActivityStatus,
			&i.PurchaseLimit,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByActivity = `-- name: ListProductsByActivity :many
SELECT id, activity_no, product_name, product_image, original_price, discount_type, discount_price, sort_order, created_at, updated_at, is_deleted
FROM sk_activity_product
WHERE activity_no = $1
  AND is_deleted = 0
ORDER BY sort_order ASC
`

func (q *Queries) ListProductsByActivity(ctx context.Context, activityNo string) ([]SkActivityProduct, error) {
	rows, err := q.db.Query(ctx, listProductsByActivity, activityNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkActivityProduct{}
	for rows.Next() {
		var i SkActivityProduct
		if err := rows.Scan(
			&i.ID,
			&i.ActivityNo,
			&i.ProductName,
			&i.ProductImage,
			&i.OriginalPrice,
			&i.DiscountType,
			&i.DiscountPrice,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSKUsByActivity = `-- name: ListSKUsByActivity :many
SELECT id, activity_no, product_id, sku_no, activity_stock, discount_type, discount_percent, discount_price, created_at, updated_at, is_deleted
FROM sk_activity_product_sku
WHERE activity_no = $1
  AND is_deleted = 0
ORDER BY id ASC
`

func (q *Queries) ListSKUsByActivity(ctx context.Context, activityNo string) ([]SkActivityProductSku, error) {
	rows, err := q.db.Query(ctx, listSKUsByActivity, activityNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkActivityProductSku{}
	for rows.Next() {
		var i SkActivityProductSku
		if err := rows.Scan(
			&i.ID,
			&i.ActivityNo,
			&i.ProductID,
			&i.SkuNo,
			&i.ActivityStock,
			&i.DiscountType,
			&i.DiscountPercent,
			&i.DiscountPrice,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :exec
UPDATE sk_activity
SET activity_name   = $2,
    start_time      = $3,
    end_time        = $4,
    activity_status = $5,
    purchase_limit  = $6,
    remark          = $7,
    updated_at      = NOW()
WHERE activity_no = $1
  AND is_deleted = 0
`

type UpdateActivityParams struct {
	ActivityNo     string      `json:"activity_no"`
	ActivityName   string      `json:"activity_name"`
	StartTime      time.Time   `json:"start_time"`
	EndTime        time.Time   `json:"end_time"`
	ActivityStatus int16       `json:"activity_status"`
	PurchaseLimit  int32       `json:"purchase_limit"`
	Remark         pgtype.Text `json:"remark"`
}

func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) error {
	_, err := q.db.Exec(ctx, updateActivity,
		arg.ActivityNo,
		arg.ActivityName,
		arg.StartTime,
		arg.EndTime,
		arg.ActivityStatus,
		arg.PurchaseLimit,
		arg.Remark,
	)
	return err
}

const updateActivityStatus = `-- name: UpdateActivityStatus :exec
UPDATE sk_activity
SET activity_status = $2,
    updated_at      = NOW()
WHERE activity_no = $1
  AND is_deleted = 0
`

type UpdateActivityStatusParams struct {
	ActivityNo     string `json:"activity_no"`
	ActivityStatus int16  `json:"activity_status"`
}

func (q *Queries) UpdateActivityStatus(ctx context.Context, arg UpdateActivityStatusParams) error {
	_, err := q.db.Exec(ctx, updateActivityStatus, arg.ActivityNo, arg.ActivityStatus)
	return err
}

const updateRuntimeStock = `-- name: UpdateRuntimeStock :exec
UPDATE sk_product
SET available_stock = available_stock - $2,
    updated_at      = NOW()
WHERE sku_no        = $1
  AND is_deleted     = 0
  AND available_stock >= $2
`

type UpdateRuntimeStockParams struct {
	SkuNo          string `json:"sku_no"`
	AvailableStock int32  `json:"available_stock"`
}

func (q *Queries) UpdateRuntimeStock(ctx context.Context, arg UpdateRuntimeStockParams) error {
	_, err := q.db.Exec(ctx, updateRuntimeStock, arg.SkuNo, arg.AvailableStock)
	return err
}
