// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// activity main table
type SkActivity struct {
	ID int64 `json:"id"`
	// unique business key for the activity
	ActivityNo   string    `json:"activity_no"`
	ActivityName string    `json:"activity_name"`
	StartTime    time.Time `json:"start_time"`
	EndTime      time.Time `json:"end_time"`
	// 0: whole period, 1: specific days/time range
	EffectiveType int16 `json:"effective_type"`
	// comma-separated day numbers, e.g. 1,2,3
	EffectiveDays pgtype.Text `json:"effective_days"`
	// daily effective start time, stored as HH:MM
	EffectiveStart pgtype.Text `json:"effective_start"`
	// daily effective end time, stored as HH:MM
	EffectiveEnd pgtype.Text `json:"effective_end"`
	// 0: draft, 1: pending, 2: live, 3: ended, 4: cancelled
	ActivityStatus int16       `json:"activity_status"`
	PurchaseLimit  int32       `json:"purchase_limit"`
	Remark         pgtype.Text `json:"remark"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	// soft delete flag, 0: active, 1: deleted
	IsDeleted int16 `json:"is_deleted"`
}

// product config per activity
type SkActivityProduct struct {
	ID            int64       `json:"id"`
	ActivityNo    string      `json:"activity_no"`
	ProductName   string      `json:"product_name"`
	ProductImage  pgtype.Text `json:"product_image"`
	OriginalPrice int64       `json:"original_price"`
	// 0: none, 1: percent, 2: fixed price
	DiscountType int16 `json:"discount_type"`
	// discount amount in cents
	DiscountPrice pgtype.Int8 `json:"discount_price"`
	SortOrder     int32       `json:"sort_order"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	IsDeleted     int16       `json:"is_deleted"`
}

// SKU-level config (price, stock) per activity product
type SkActivityProductSku struct {
	ID            int64  `json:"id"`
	ActivityNo    string `json:"activity_no"`
	ProductID     int64  `json:"product_id"`
	SkuNo         string `json:"sku_no"`
	ActivityStock int32  `json:"activity_stock"`
	// 0: none, 1: percent, 2: fixed price
	DiscountType int16 `json:"discount_type"`
	// percentage discount, e.g. 20 means 20% off
	DiscountPercent pgtype.Int4 `json:"discount_percent"`
	// fixed discount price in cents
	DiscountPrice pgtype.Int8 `json:"discount_price"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	IsDeleted     int16       `json:"is_deleted"`
}

// runtime product state generated when activity goes live
type SkProduct struct {
	ID            int64       `json:"id"`
	ActivityNo    string      `json:"activity_no"`
	ProductName   string      `json:"product_name"`
	ProductImage  pgtype.Text `json:"product_image"`
	SkuNo         string      `json:"sku_no"`
	OriginalPrice int64       `json:"original_price"`
	// final seckill price in cents
	SeckillPrice int64 `json:"seckill_price"`
	TotalStock   int32 `json:"total_stock"`
	// remaining stock available for purchase
	AvailableStock int32 `json:"available_stock"`
	// max quantity per user per activity
	LimitQuantity int32     `json:"limit_quantity"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	IsDeleted     int16     `json:"is_deleted"`
}
