// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/stock/v1/stock.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v1 "seckill-api/activity/v1"
	v11 "seckill-api/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockService_Peek_FullMethodName                     = "/seckill.api.stock.StockService/Peek"
	StockService_Deduct_FullMethodName                   = "/seckill.api.stock.StockService/Deduct"
	StockService_Release_FullMethodName                  = "/seckill.api.stock.StockService/Release"
	StockService_CleanupActivity_FullMethodName          = "/seckill.api.stock.StockService/CleanupActivity"
	StockService_CleanupActivityPurchases_FullMethodName = "/seckill.api.stock.StockService/CleanupActivityPurchases"
)

// StockServiceClient is the client API for StockService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockServiceClient interface {
	Peek(ctx context.Context, in *v1.SKURequest, opts ...grpc.CallOption) (*StockResponse, error)
	Deduct(ctx context.Context, in *DeductRequest, opts ...grpc.CallOption) (*v11.BoolResponse, error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CleanupActivity(ctx context.Context, in *StockCleanupRequest, opts ...grpc.CallOption) (*StockCleanupResponse, error)
	CleanupActivityPurchases(ctx context.Context, in *ActivityPurchaseCleanupRequest, opts ...grpc.CallOption) (*StockCleanupResponse, error)
}

type stockServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockServiceClient(cc grpc.ClientConnInterface) StockServiceClient {
	return &stockServiceClient{cc}
}

func (c *stockServiceClient) Peek(ctx context.Context, in *v1.SKURequest, opts ...grpc.CallOption) (*StockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockResponse)
	err := c.cc.Invoke(ctx, StockService_Peek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) Deduct(ctx context.Context, in *DeductRequest, opts ...grpc.CallOption) (*v11.BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.BoolResponse)
	err := c.cc.Invoke(ctx, StockService_Deduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StockService_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) CleanupActivity(ctx context.Context, in *StockCleanupRequest, opts ...grpc.CallOption) (*StockCleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockCleanupResponse)
	err := c.cc.Invoke(ctx, StockService_CleanupActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockServiceClient) CleanupActivityPurchases(ctx context.Context, in *ActivityPurchaseCleanupRequest, opts ...grpc.CallOption) (*StockCleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockCleanupResponse)
	err := c.cc.Invoke(ctx, StockService_CleanupActivityPurchases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockServiceServer is the server API for StockService service.
// All implementations must embed UnimplementedStockServiceServer
// for forward compatibility.
type StockServiceServer interface {
	Peek(context.Context, *v1.SKURequest) (*StockResponse, error)
	Deduct(context.Context, *DeductRequest) (*v11.BoolResponse, error)
	Release(context.Context, *ReleaseRequest) (*emptypb.Empty, error)
	CleanupActivity(context.Context, *StockCleanupRequest) (*StockCleanupResponse, error)
	CleanupActivityPurchases(context.Context, *ActivityPurchaseCleanupRequest) (*StockCleanupResponse, error)
	mustEmbedUnimplementedStockServiceServer()
}

// UnimplementedStockServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockServiceServer struct{}

func (UnimplementedStockServiceServer) Peek(context.Context, *v1.SKURequest) (*StockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Peek not implemented")
}
func (UnimplementedStockServiceServer) Deduct(context.Context, *DeductRequest) (*v11.BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deduct not implemented")
}
func (UnimplementedStockServiceServer) Release(context.Context, *ReleaseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedStockServiceServer) CleanupActivity(context.Context, *StockCleanupRequest) (*StockCleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupActivity not implemented")
}
func (UnimplementedStockServiceServer) CleanupActivityPurchases(context.Context, *ActivityPurchaseCleanupRequest) (*StockCleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupActivityPurchases not implemented")
}
func (UnimplementedStockServiceServer) mustEmbedUnimplementedStockServiceServer() {}
func (UnimplementedStockServiceServer) testEmbeddedByValue()                      {}

// UnsafeStockServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockServiceServer will
// result in compilation errors.
type UnsafeStockServiceServer interface {
	mustEmbedUnimplementedStockServiceServer()
}

func RegisterStockServiceServer(s grpc.ServiceRegistrar, srv StockServiceServer) {
	// If the following call panics, it indicates UnimplementedStockServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockService_ServiceDesc, srv)
}

func _StockService_Peek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.SKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).Peek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_Peek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).Peek(ctx, req.(*v1.SKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_Deduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).Deduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_Deduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).Deduct(ctx, req.(*DeductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_CleanupActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockCleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).CleanupActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_CleanupActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).CleanupActivity(ctx, req.(*StockCleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockService_CleanupActivityPurchases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityPurchaseCleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockServiceServer).CleanupActivityPurchases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockService_CleanupActivityPurchases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockServiceServer).CleanupActivityPurchases(ctx, req.(*ActivityPurchaseCleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockService_ServiceDesc is the grpc.ServiceDesc for StockService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.api.stock.StockService",
	HandlerType: (*StockServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Peek",
			Handler:    _StockService_Peek_Handler,
		},
		{
			MethodName: "Deduct",
			Handler:    _StockService_Deduct_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _StockService_Release_Handler,
		},
		{
			MethodName: "CleanupActivity",
			Handler:    _StockService_CleanupActivity_Handler,
		},
		{
			MethodName: "CleanupActivityPurchases",
			Handler:    _StockService_CleanupActivityPurchases_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/stock/v1/stock.proto",
}
