// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/stock/v1/stock.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	v1 "seckill-api/activity/v1"
	v11 "seckill-api/common/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         int64                  `protobuf:"varint,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockResponse) Reset() {
	*x = StockResponse{}
	mi := &file_api_stock_v1_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockResponse) ProtoMessage() {}

func (x *StockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stock_v1_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockResponse.ProtoReflect.Descriptor instead.
func (*StockResponse) Descriptor() ([]byte, []int) {
	return file_api_stock_v1_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockResponse) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type DeductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	SkuNo         string                 `protobuf:"bytes,2,opt,name=sku_no,json=skuNo,proto3" json:"sku_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PurchaseLimit int64                  `protobuf:"varint,5,opt,name=purchase_limit,json=purchaseLimit,proto3" json:"purchase_limit,omitempty"`
	OrderNo       string                 `protobuf:"bytes,6,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductRequest) Reset() {
	*x = DeductRequest{}
	mi := &file_api_stock_v1_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductRequest) ProtoMessage() {}

func (x *DeductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stock_v1_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductRequest.ProtoReflect.Descriptor instead.
func (*DeductRequest) Descriptor() ([]byte, []int) {
	return file_api_stock_v1_stock_proto_rawDescGZIP(), []int{1}
}

func (x *DeductRequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *DeductRequest) GetSkuNo() string {
	if x != nil {
		return x.SkuNo
	}
	return ""
}

func (x *DeductRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeductRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *DeductRequest) GetPurchaseLimit() int64 {
	if x != nil {
		return x.PurchaseLimit
	}
	return 0
}

func (x *DeductRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	SkuNo         string                 `protobuf:"bytes,2,opt,name=sku_no,json=skuNo,proto3" json:"sku_no,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderNo       string                 `protobuf:"bytes,5,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_stock_v1_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stock_v1_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_stock_v1_stock_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseRequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *ReleaseRequest) GetSkuNo() string {
	if x != nil {
		return x.SkuNo
	}
	return ""
}

func (x *ReleaseRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReleaseRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReleaseRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type StockCleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	SkuNos        []string               `protobuf:"bytes,2,rep,name=sku_nos,json=skuNos,proto3" json:"sku_nos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockCleanupRequest) Reset() {
	*x = StockCleanupRequest{}
	mi := &file_api_stock_v1_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockCleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockCleanupRequest) ProtoMessage() {}

func (x *StockCleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stock_v1_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockCleanupRequest.ProtoReflect.Descriptor instead.
func (*StockCleanupRequest) Descriptor() ([]byte, []int) {
	return file_api_stock_v1_stock_proto_rawDescGZIP(), []int{3}
}

func (x *StockCleanupRequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *StockCleanupRequest) GetSkuNos() []string {
	if x != nil {
		return x.SkuNos
	}
	return nil
}

type StockCleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockCleanupResponse) Reset() {
	*x = StockCleanupResponse{}
	mi := &file_api_stock_v1_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockCleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockCleanupResponse) ProtoMessage() {}

func (x *StockCleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_stock_v1_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockCleanupResponse.ProtoReflect.Descriptor instead.
func (*StockCleanupResponse) Descriptor() ([]byte, []int) {
	return file_api_stock_v1_stock_proto_rawDescGZIP(), []int{4}
}

func (x *StockCleanupResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

type ActivityPurchaseCleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityPurchaseCleanupRequest) Reset() {
	*x = ActivityPurchaseCleanupRequest{}
	mi := &file_api_stock_v1_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityPurchaseCleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityPurchaseCleanupRequest) ProtoMessage() {}

func (x *ActivityPurchaseCleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_stock_v1_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityPurchaseCleanupRequest.ProtoReflect.Descriptor instead.
func (*ActivityPurchaseCleanupRequest) Descriptor() ([]byte, []int) {
	return file_api_stock_v1_stock_proto_rawDescGZIP(), []int{5}
}

func (x *ActivityPurchaseCleanupRequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

var File_api_stock_v1_stock_proto protoreflect.FileDescriptor

const file_api_stock_v1_stock_proto_rawDesc = "" +
	"\n" +
	"\x18api/stock/v1/stock.proto\x12\x11seckill.api.stock\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1eapi/activity/v1/activity.proto\x1a\x1aapi/common/v1/common.proto\"%\n" +
	"\rStockResponse\x12\x14\n" +
	"\x05stock\x18\x01 \x01(\x03R\x05stock\"\xbe\x01\n" +
	"\rDeductRequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x12\x15\n" +
	"\x06sku_no\x18\x02 \x01(\tR\x05skuNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12%\n" +
	"\x0epurchase_limit\x18\x05 \x01(\x03R\rpurchaseLimit\x12\x19\n" +
	"\border_no\x18\x06 \x01(\tR\aorderNo\"\x98\x01\n" +
	"\x0eReleaseRequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x12\x15\n" +
	"\x06sku_no\x18\x02 \x01(\tR\x05skuNo\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x19\n" +
	"\border_no\x18\x05 \x01(\tR\aorderNo\"O\n" +
	"\x13StockCleanupRequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x12\x17\n" +
	"\asku_nos\x18\x02 \x03(\tR\x06skuNos\"0\n" +
	"\x14StockCleanupResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\"A\n" +
	"\x1eActivityPurchaseCleanupRequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo2\xca\x03\n" +
	"\fStockService\x12J\n" +
	"\x04Peek\x12 .seckill.api.activity.SKURequest\x1a .seckill.api.stock.StockResponse\x12L\n" +
	"\x06Deduct\x12 .seckill.api.stock.DeductRequest\x1a .seckill.api.common.BoolResponse\x12D\n" +
	"\aRelease\x12!.seckill.api.stock.ReleaseRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\x0fCleanupActivity\x12&.seckill.api.stock.StockCleanupRequest\x1a'.seckill.api.stock.StockCleanupResponse\x12v\n" +
	"\x18CleanupActivityPurchases\x121.seckill.api.stock.ActivityPurchaseCleanupRequest\x1a'.seckill.api.stock.StockCleanupResponseB\x19Z\x17seckill-api/stock/v1;v1b\x06proto3"

var (
	file_api_stock_v1_stock_proto_rawDescOnce sync.Once
	file_api_stock_v1_stock_proto_rawDescData []byte
)

func file_api_stock_v1_stock_proto_rawDescGZIP() []byte {
	file_api_stock_v1_stock_proto_rawDescOnce.Do(func() {
		file_api_stock_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_stock_v1_stock_proto_rawDesc), len(file_api_stock_v1_stock_proto_rawDesc)))
	})
	return file_api_stock_v1_stock_proto_rawDescData
}

var file_api_stock_v1_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_stock_v1_stock_proto_goTypes = []any{
	(*StockResponse)(nil),                  // 0: seckill.api.stock.StockResponse
	(*DeductRequest)(nil),                  // 1: seckill.api.stock.DeductRequest
	(*ReleaseRequest)(nil),                 // 2: seckill.api.stock.ReleaseRequest
	(*StockCleanupRequest)(nil),            // 3: seckill.api.stock.StockCleanupRequest
	(*StockCleanupResponse)(nil),           // 4: seckill.api.stock.StockCleanupResponse
	(*ActivityPurchaseCleanupRequest)(nil), // 5: seckill.api.stock.ActivityPurchaseCleanupRequest
	(*v1.SKURequest)(nil),                  // 6: seckill.api.activity.SKURequest
	(*v11.BoolResponse)(nil),               // 7: seckill.api.common.BoolResponse
	(*emptypb.Empty)(nil),                  // 8: google.protobuf.Empty
}
var file_api_stock_v1_stock_proto_depIdxs = []int32{
	6, // 0: seckill.api.stock.StockService.Peek:input_type -> seckill.api.activity.SKURequest
	1, // 1: seckill.api.stock.StockService.Deduct:input_type -> seckill.api.stock.DeductRequest
	2, // 2: seckill.api.stock.StockService.Release:input_type -> seckill.api.stock.ReleaseRequest
	3, // 3: seckill.api.stock.StockService.CleanupActivity:input_type -> seckill.api.stock.StockCleanupRequest
	5, // 4: seckill.api.stock.StockService.CleanupActivityPurchases:input_type -> seckill.api.stock.ActivityPurchaseCleanupRequest
	0, // 5: seckill.api.stock.StockService.Peek:output_type -> seckill.api.stock.StockResponse
	7, // 6: seckill.api.stock.StockService.Deduct:output_type -> seckill.api.common.BoolResponse
	8, // 7: seckill.api.stock.StockService.Release:output_type -> google.protobuf.Empty
	4, // 8: seckill.api.stock.StockService.CleanupActivity:output_type -> seckill.api.stock.StockCleanupResponse
	4, // 9: seckill.api.stock.StockService.CleanupActivityPurchases:output_type -> seckill.api.stock.StockCleanupResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_stock_v1_stock_proto_init() }
func file_api_stock_v1_stock_proto_init() {
	if File_api_stock_v1_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_stock_v1_stock_proto_rawDesc), len(file_api_stock_v1_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stock_v1_stock_proto_goTypes,
		DependencyIndexes: file_api_stock_v1_stock_proto_depIdxs,
		MessageInfos:      file_api_stock_v1_stock_proto_msgTypes,
	}.Build()
	File_api_stock_v1_stock_proto = out.File
	file_api_stock_v1_stock_proto_goTypes = nil
	file_api_stock_v1_stock_proto_depIdxs = nil
}
