// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type SkRiskRecord struct {
	ID          int64       `json:"id"`
	UserID      int64       `json:"user_id"`
	ActionType  string      `json:"action_type"`
	RiskLevel   int16       `json:"risk_level"`
	RequestIp   pgtype.Text `json:"request_ip"`
	RequestInfo pgtype.Text `json:"request_info"`
	CreatedAt   time.Time   `json:"created_at"`
}
