// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: risk.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredRecords = `-- name: CleanupExpiredRecords :exec
DELETE FROM sk_risk_record WHERE created_at < $1
`

func (q *Queries) CleanupExpiredRecords(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, cleanupExpiredRecords, createdAt)
	return err
}

const countRecentActions = `-- name: CountRecentActions :one
SELECT COUNT(*) FROM sk_risk_record
WHERE user_id = $1 AND action_type = $2 AND created_at > $3
`

type CountRecentActionsParams struct {
	UserID     int64     `json:"user_id"`
	ActionType string    `json:"action_type"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CountRecentActions(ctx context.Context, arg CountRecentActionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentActions, arg.UserID, arg.ActionType, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRiskRecord = `-- name: CreateRiskRecord :exec
INSERT INTO sk_risk_record (user_id, action_type, risk_level, request_ip, request_info)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRiskRecordParams struct {
	UserID      int64       `json:"user_id"`
	ActionType  string      `json:"action_type"`
	RiskLevel   int16       `json:"risk_level"`
	RequestIp   pgtype.Text `json:"request_ip"`
	RequestInfo pgtype.Text `json:"request_info"`
}

func (q *Queries) CreateRiskRecord(ctx context.Context, arg CreateRiskRecordParams) error {
	_, err := q.db.Exec(ctx, createRiskRecord,
		arg.UserID,
		arg.ActionType,
		arg.RiskLevel,
		arg.RequestIp,
		arg.RequestInfo,
	)
	return err
}

const hasHighRiskRecord = `-- name: HasHighRiskRecord :one
SELECT EXISTS(
    SELECT 1 FROM sk_risk_record
    WHERE user_id = $1 AND risk_level >= 2 AND created_at > $2
)
`

type HasHighRiskRecordParams struct {
	UserID    int64     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) HasHighRiskRecord(ctx context.Context, arg HasHighRiskRecordParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasHighRiskRecord, arg.UserID, arg.CreatedAt)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listRiskRecordsByUser = `-- name: ListRiskRecordsByUser :many
SELECT id, user_id, action_type, risk_level, request_ip, request_info, created_at FROM sk_risk_record
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRiskRecordsByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListRiskRecordsByUser(ctx context.Context, arg ListRiskRecordsByUserParams) ([]SkRiskRecord, error) {
	rows, err := q.db.Query(ctx, listRiskRecordsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkRiskRecord{}
	for rows.Next() {
		var i SkRiskRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActionType,
			&i.RiskLevel,
			&i.RequestIp,
			&i.RequestInfo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
