// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/risk/v1/risk.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v1 "seckill-api/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskService_MarkSuspicious_FullMethodName          = "/seckill.api.risk.RiskService/MarkSuspicious"
	RiskService_Evaluate_FullMethodName                = "/seckill.api.risk.RiskService/Evaluate"
	RiskService_RecordAction_FullMethodName            = "/seckill.api.risk.RiskService/RecordAction"
	RiskService_IsRiskUser_FullMethodName              = "/seckill.api.risk.RiskService/IsRiskUser"
	RiskService_CleanupExpiredRiskUsers_FullMethodName = "/seckill.api.risk.RiskService/CleanupExpiredRiskUsers"
)

// RiskServiceClient is the client API for RiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskServiceClient interface {
	MarkSuspicious(ctx context.Context, in *RiskMarkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Evaluate(ctx context.Context, in *RiskEvaluateRequest, opts ...grpc.CallOption) (*RiskEvaluationResponse, error)
	RecordAction(ctx context.Context, in *RiskRecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IsRiskUser(ctx context.Context, in *RiskUserRequest, opts ...grpc.CallOption) (*v1.BoolResponse, error)
	CleanupExpiredRiskUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RiskCleanupResponse, error)
}

type riskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskServiceClient(cc grpc.ClientConnInterface) RiskServiceClient {
	return &riskServiceClient{cc}
}

func (c *riskServiceClient) MarkSuspicious(ctx context.Context, in *RiskMarkRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RiskService_MarkSuspicious_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) Evaluate(ctx context.Context, in *RiskEvaluateRequest, opts ...grpc.CallOption) (*RiskEvaluationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskEvaluationResponse)
	err := c.cc.Invoke(ctx, RiskService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) RecordAction(ctx context.Context, in *RiskRecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RiskService_RecordAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) IsRiskUser(ctx context.Context, in *RiskUserRequest, opts ...grpc.CallOption) (*v1.BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.BoolResponse)
	err := c.cc.Invoke(ctx, RiskService_IsRiskUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) CleanupExpiredRiskUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RiskCleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskCleanupResponse)
	err := c.cc.Invoke(ctx, RiskService_CleanupExpiredRiskUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServiceServer is the server API for RiskService service.
// All implementations must embed UnimplementedRiskServiceServer
// for forward compatibility.
type RiskServiceServer interface {
	MarkSuspicious(context.Context, *RiskMarkRequest) (*emptypb.Empty, error)
	Evaluate(context.Context, *RiskEvaluateRequest) (*RiskEvaluationResponse, error)
	RecordAction(context.Context, *RiskRecordRequest) (*emptypb.Empty, error)
	IsRiskUser(context.Context, *RiskUserRequest) (*v1.BoolResponse, error)
	CleanupExpiredRiskUsers(context.Context, *emptypb.Empty) (*RiskCleanupResponse, error)
	mustEmbedUnimplementedRiskServiceServer()
}

// UnimplementedRiskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskServiceServer struct{}

func (UnimplementedRiskServiceServer) MarkSuspicious(context.Context, *RiskMarkRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkSuspicious not implemented")
}
func (UnimplementedRiskServiceServer) Evaluate(context.Context, *RiskEvaluateRequest) (*RiskEvaluationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedRiskServiceServer) RecordAction(context.Context, *RiskRecordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordAction not implemented")
}
func (UnimplementedRiskServiceServer) IsRiskUser(context.Context, *RiskUserRequest) (*v1.BoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsRiskUser not implemented")
}
func (UnimplementedRiskServiceServer) CleanupExpiredRiskUsers(context.Context, *emptypb.Empty) (*RiskCleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CleanupExpiredRiskUsers not implemented")
}
func (UnimplementedRiskServiceServer) mustEmbedUnimplementedRiskServiceServer() {}
func (UnimplementedRiskServiceServer) testEmbeddedByValue()                     {}

// UnsafeRiskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskServiceServer will
// result in compilation errors.
type UnsafeRiskServiceServer interface {
	mustEmbedUnimplementedRiskServiceServer()
}

func RegisterRiskServiceServer(s grpc.ServiceRegistrar, srv RiskServiceServer) {
	// If the following call panics, it indicates UnimplementedRiskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskService_ServiceDesc, srv)
}

func _RiskService_MarkSuspicious_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskMarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).MarkSuspicious(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_MarkSuspicious_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).MarkSuspicious(ctx, req.(*RiskMarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskEvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).Evaluate(ctx, req.(*RiskEvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_RecordAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).RecordAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_RecordAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).RecordAction(ctx, req.(*RiskRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_IsRiskUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).IsRiskUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_IsRiskUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).IsRiskUser(ctx, req.(*RiskUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_CleanupExpiredRiskUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).CleanupExpiredRiskUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_CleanupExpiredRiskUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).CleanupExpiredRiskUsers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskService_ServiceDesc is the grpc.ServiceDesc for RiskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.api.risk.RiskService",
	HandlerType: (*RiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MarkSuspicious",
			Handler:    _RiskService_MarkSuspicious_Handler,
		},
		{
			MethodName: "Evaluate",
			Handler:    _RiskService_Evaluate_Handler,
		},
		{
			MethodName: "RecordAction",
			Handler:    _RiskService_RecordAction_Handler,
		},
		{
			MethodName: "IsRiskUser",
			Handler:    _RiskService_IsRiskUser_Handler,
		},
		{
			MethodName: "CleanupExpiredRiskUsers",
			Handler:    _RiskService_CleanupExpiredRiskUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/risk/v1/risk.proto",
}
