// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/risk/v1/risk.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	v1 "seckill-api/activity/v1"
	v11 "seckill-api/common/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiskEvaluation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Risk          bool                   `protobuf:"varint,1,opt,name=risk,proto3" json:"risk,omitempty"`
	Level         int64                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskEvaluation) Reset() {
	*x = RiskEvaluation{}
	mi := &file_api_risk_v1_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskEvaluation) ProtoMessage() {}

func (x *RiskEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_api_risk_v1_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskEvaluation.ProtoReflect.Descriptor instead.
func (*RiskEvaluation) Descriptor() ([]byte, []int) {
	return file_api_risk_v1_risk_proto_rawDescGZIP(), []int{0}
}

func (x *RiskEvaluation) GetRisk() bool {
	if x != nil {
		return x.Risk
	}
	return false
}

func (x *RiskEvaluation) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RiskEvaluation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RiskRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	RiskLevel     int64                  `protobuf:"varint,3,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RequestIp     string                 `protobuf:"bytes,4,opt,name=request_ip,json=requestIp,proto3" json:"request_ip,omitempty"`
	RequestInfo   string                 `protobuf:"bytes,5,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskRecord) Reset() {
	*x = RiskRecord{}
	mi := &file_api_risk_v1_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRecord) ProtoMessage() {}

func (x *RiskRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_risk_v1_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRecord.ProtoReflect.Descriptor instead.
func (*RiskRecord) Descriptor() ([]byte, []int) {
	return file_api_risk_v1_risk_proto_rawDescGZIP(), []int{1}
}

func (x *RiskRecord) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RiskRecord) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *RiskRecord) GetRiskLevel() int64 {
	if x != nil {
		return x.RiskLevel
	}
	return 0
}

func (x *RiskRecord) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *RiskRecord) GetRequestInfo() string {
	if x != nil {
		return x.RequestInfo
	}
	return ""
}

func (x *RiskRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RiskMarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *v1.Activity           `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestIp     string                 `protobuf:"bytes,3,opt,name=request_ip,json=requestIp,proto3" json:"request_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskMarkRequest) Reset() {
	*x = RiskMarkRequest{}
	mi := &file_api_risk_v1_risk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskMarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskMarkRequest) ProtoMessage() {}

func (x *RiskMarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_risk_v1_risk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskMarkRequest.ProtoReflect.Descriptor instead.
func (*RiskMarkRequest) Descriptor() ([]byte, []int) {
	return file_api_risk_v1_risk_proto_rawDescGZIP(), []int{2}
}

func (x *RiskMarkRequest) GetActivity() *v1.Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *RiskMarkRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RiskMarkRequest) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

type RiskUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskUserRequest) Reset() {
	*x = RiskUserRequest{}
	mi := &file_api_risk_v1_risk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskUserRequest) ProtoMessage() {}

func (x *RiskUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_risk_v1_risk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskUserRequest.ProtoReflect.Descriptor instead.
func (*RiskUserRequest) Descriptor() ([]byte, []int) {
	return file_api_risk_v1_risk_proto_rawDescGZIP(), []int{3}
}

func (x *RiskUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RiskEvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestIp     string                 `protobuf:"bytes,2,opt,name=request_ip,json=requestIp,proto3" json:"request_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskEvaluateRequest) Reset() {
	*x = RiskEvaluateRequest{}
	mi := &file_api_risk_v1_risk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskEvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskEvaluateRequest) ProtoMessage() {}

func (x *RiskEvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_risk_v1_risk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskEvaluateRequest.ProtoReflect.Descriptor instead.
func (*RiskEvaluateRequest) Descriptor() ([]byte, []int) {
	return file_api_risk_v1_risk_proto_rawDescGZIP(), []int{4}
}

func (x *RiskEvaluateRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RiskEvaluateRequest) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

type RiskEvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evaluation    *RiskEvaluation        `protobuf:"bytes,1,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskEvaluationResponse) Reset() {
	*x = RiskEvaluationResponse{}
	mi := &file_api_risk_v1_risk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskEvaluationResponse) ProtoMessage() {}

func (x *RiskEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_risk_v1_risk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskEvaluationResponse.ProtoReflect.Descriptor instead.
func (*RiskEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_api_risk_v1_risk_proto_rawDescGZIP(), []int{5}
}

func (x *RiskEvaluationResponse) GetEvaluation() *RiskEvaluation {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

type RiskRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *RiskRecord            `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskRecordRequest) Reset() {
	*x = RiskRecordRequest{}
	mi := &file_api_risk_v1_risk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskRecordRequest) ProtoMessage() {}

func (x *RiskRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_risk_v1_risk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskRecordRequest.ProtoReflect.Descriptor instead.
func (*RiskRecordRequest) Descriptor() ([]byte, []int) {
	return file_api_risk_v1_risk_proto_rawDescGZIP(), []int{6}
}

func (x *RiskRecordRequest) GetRecord() *RiskRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type RiskCleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskCleanupResponse) Reset() {
	*x = RiskCleanupResponse{}
	mi := &file_api_risk_v1_risk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskCleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskCleanupResponse) ProtoMessage() {}

func (x *RiskCleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_risk_v1_risk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskCleanupResponse.ProtoReflect.Descriptor instead.
func (*RiskCleanupResponse) Descriptor() ([]byte, []int) {
	return file_api_risk_v1_risk_proto_rawDescGZIP(), []int{7}
}

func (x *RiskCleanupResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_api_risk_v1_risk_proto protoreflect.FileDescriptor

const file_api_risk_v1_risk_proto_rawDesc = "" +
	"\n" +
	"\x16api/risk/v1/risk.proto\x12\x10seckill.api.risk\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eapi/activity/v1/activity.proto\x1a\x1aapi/common/v1/common.proto\"R\n" +
	"\x0eRiskEvaluation\x12\x12\n" +
	"\x04risk\x18\x01 \x01(\bR\x04risk\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x03R\x05level\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xe2\x01\n" +
	"\n" +
	"RiskRecord\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x03 \x01(\x03R\triskLevel\x12\x1d\n" +
	"\n" +
	"request_ip\x18\x04 \x01(\tR\trequestIp\x12!\n" +
	"\frequest_info\x18\x05 \x01(\tR\vrequestInfo\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x85\x01\n" +
	"\x0fRiskMarkRequest\x12:\n" +
	"\bactivity\x18\x01 \x01(\v2\x1e.seckill.api.activity.ActivityR\bactivity\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"request_ip\x18\x03 \x01(\tR\trequestIp\"*\n" +
	"\x0fRiskUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"M\n" +
	"\x13RiskEvaluateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"request_ip\x18\x02 \x01(\tR\trequestIp\"Z\n" +
	"\x16RiskEvaluationResponse\x12@\n" +
	"\n" +
	"evaluation\x18\x01 \x01(\v2 .seckill.api.risk.RiskEvaluationR\n" +
	"evaluation\"I\n" +
	"\x11RiskRecordRequest\x124\n" +
	"\x06record\x18\x01 \x01(\v2\x1c.seckill.api.risk.RiskRecordR\x06record\"/\n" +
	"\x13RiskCleanupResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted2\xb1\x03\n" +
	"\vRiskService\x12K\n" +
	"\x0eMarkSuspicious\x12!.seckill.api.risk.RiskMarkRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\bEvaluate\x12%.seckill.api.risk.RiskEvaluateRequest\x1a(.seckill.api.risk.RiskEvaluationResponse\x12K\n" +
	"\fRecordAction\x12#.seckill.api.risk.RiskRecordRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\n" +
	"IsRiskUser\x12!.seckill.api.risk.RiskUserRequest\x1a .seckill.api.common.BoolResponse\x12X\n" +
	"\x17CleanupExpiredRiskUsers\x12\x16.google.protobuf.Empty\x1a%.seckill.api.risk.RiskCleanupResponseB\x18Z\x16seckill-api/risk/v1;v1b\x06proto3"

var (
	file_api_risk_v1_risk_proto_rawDescOnce sync.Once
	file_api_risk_v1_risk_proto_rawDescData []byte
)

func file_api_risk_v1_risk_proto_rawDescGZIP() []byte {
	file_api_risk_v1_risk_proto_rawDescOnce.Do(func() {
		file_api_risk_v1_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_risk_v1_risk_proto_rawDesc), len(file_api_risk_v1_risk_proto_rawDesc)))
	})
	return file_api_risk_v1_risk_proto_rawDescData
}

var file_api_risk_v1_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_risk_v1_risk_proto_goTypes = []any{
	(*RiskEvaluation)(nil),         // 0: seckill.api.risk.RiskEvaluation
	(*RiskRecord)(nil),             // 1: seckill.api.risk.RiskRecord
	(*RiskMarkRequest)(nil),        // 2: seckill.api.risk.RiskMarkRequest
	(*RiskUserRequest)(nil),        // 3: seckill.api.risk.RiskUserRequest
	(*RiskEvaluateRequest)(nil),    // 4: seckill.api.risk.RiskEvaluateRequest
	(*RiskEvaluationResponse)(nil), // 5: seckill.api.risk.RiskEvaluationResponse
	(*RiskRecordRequest)(nil),      // 6: seckill.api.risk.RiskRecordRequest
	(*RiskCleanupResponse)(nil),    // 7: seckill.api.risk.RiskCleanupResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*v1.Activity)(nil),            // 9: seckill.api.activity.Activity
	(*emptypb.Empty)(nil),          // 10: google.protobuf.Empty
	(*v11.BoolResponse)(nil),       // 11: seckill.api.common.BoolResponse
}
var file_api_risk_v1_risk_proto_depIdxs = []int32{
	8,  // 0: seckill.api.risk.RiskRecord.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: seckill.api.risk.RiskMarkRequest.activity:type_name -> seckill.api.activity.Activity
	0,  // 2: seckill.api.risk.RiskEvaluationResponse.evaluation:type_name -> seckill.api.risk.RiskEvaluation
	1,  // 3: seckill.api.risk.RiskRecordRequest.record:type_name -> seckill.api.risk.RiskRecord
	2,  // 4: seckill.api.risk.RiskService.MarkSuspicious:input_type -> seckill.api.risk.RiskMarkRequest
	4,  // 5: seckill.api.risk.RiskService.Evaluate:input_type -> seckill.api.risk.RiskEvaluateRequest
	6,  // 6: seckill.api.risk.RiskService.RecordAction:input_type -> seckill.api.risk.RiskRecordRequest
	3,  // 7: seckill.api.risk.RiskService.IsRiskUser:input_type -> seckill.api.risk.RiskUserRequest
	10, // 8: seckill.api.risk.RiskService.CleanupExpiredRiskUsers:input_type -> google.protobuf.Empty
	10, // 9: seckill.api.risk.RiskService.MarkSuspicious:output_type -> google.protobuf.Empty
	5,  // 10: seckill.api.risk.RiskService.Evaluate:output_type -> seckill.api.risk.RiskEvaluationResponse
	10, // 11: seckill.api.risk.RiskService.RecordAction:output_type -> google.protobuf.Empty
	11, // 12: seckill.api.risk.RiskService.IsRiskUser:output_type -> seckill.api.common.BoolResponse
	7,  // 13: seckill.api.risk.RiskService.CleanupExpiredRiskUsers:output_type -> seckill.api.risk.RiskCleanupResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_risk_v1_risk_proto_init() }
func file_api_risk_v1_risk_proto_init() {
	if File_api_risk_v1_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_risk_v1_risk_proto_rawDesc), len(file_api_risk_v1_risk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_risk_v1_risk_proto_goTypes,
		DependencyIndexes: file_api_risk_v1_risk_proto_depIdxs,
		MessageInfos:      file_api_risk_v1_risk_proto_msgTypes,
	}.Build()
	File_api_risk_v1_risk_proto = out.File
	file_api_risk_v1_risk_proto_goTypes = nil
	file_api_risk_v1_risk_proto_depIdxs = nil
}
