// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TFreeCard struct {
	ID          int64              `json:"id"`
	CardNo      string             `json:"card_no"`
	CardName    pgtype.Text        `json:"card_name"`
	FaceValue   int64              `json:"face_value"`
	UserID      pgtype.Int8        `json:"user_id"`
	OrderNo     pgtype.Text        `json:"order_no"`
	Status      int16              `json:"status"`
	ValidDays   int32              `json:"valid_days"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	ExpireAt    pgtype.Timestamptz `json:"expire_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type TPayment struct {
	ID            int64              `json:"id"`
	PaymentNo     string             `json:"payment_no"`
	OrderNo       string             `json:"order_no"`
	UserID        int64              `json:"user_id"`
	PayAmount     int64              `json:"pay_amount"`
	PayChannel    string             `json:"pay_channel"`
	PayStatus     int16              `json:"pay_status"`
	TransactionNo pgtype.Text        `json:"transaction_no"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type TUser struct {
	ID          int64       `json:"id"`
	Username    string      `json:"username"`
	Phone       pgtype.Text `json:"phone"`
	Nickname    pgtype.Text `json:"nickname"`
	MemberLevel int16       `json:"member_level"`
	Status      int16       `json:"status"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
