// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: support.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateCard = `-- name: ActivateCard :exec
UPDATE t_free_card
SET user_id = $2, order_no = $3, status = 1, activated_at = NOW(), expire_at = NOW() + (valid_days || ' days')::interval, updated_at = NOW()
WHERE card_no = $1
`

type ActivateCardParams struct {
	CardNo  string      `json:"card_no"`
	UserID  pgtype.Int8 `json:"user_id"`
	OrderNo pgtype.Text `json:"order_no"`
}

func (q *Queries) ActivateCard(ctx context.Context, arg ActivateCardParams) error {
	_, err := q.db.Exec(ctx, activateCard, arg.CardNo, arg.UserID, arg.OrderNo)
	return err
}

const createCard = `-- name: CreateCard :exec
INSERT INTO t_free_card (card_no, card_name, face_value, valid_days)
VALUES ($1, $2, $3, $4)
`

type CreateCardParams struct {
	CardNo    string      `json:"card_no"`
	CardName  pgtype.Text `json:"card_name"`
	FaceValue int64       `json:"face_value"`
	ValidDays int32       `json:"valid_days"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) error {
	_, err := q.db.Exec(ctx, createCard,
		arg.CardNo,
		arg.CardName,
		arg.FaceValue,
		arg.ValidDays,
	)
	return err
}

const createPayment = `-- name: CreatePayment :exec
INSERT INTO t_payment (payment_no, order_no, user_id, pay_amount, pay_channel, pay_status)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePaymentParams struct {
	PaymentNo  string `json:"payment_no"`
	OrderNo    string `json:"order_no"`
	UserID     int64  `json:"user_id"`
	PayAmount  int64  `json:"pay_amount"`
	PayChannel string `json:"pay_channel"`
	PayStatus  int16  `json:"pay_status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.Exec(ctx, createPayment,
		arg.PaymentNo,
		arg.OrderNo,
		arg.UserID,
		arg.PayAmount,
		arg.PayChannel,
		arg.PayStatus,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO t_user (username, phone, nickname, member_level, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	Username    string      `json:"username"`
	Phone       pgtype.Text `json:"phone"`
	Nickname    pgtype.Text `json:"nickname"`
	MemberLevel int16       `json:"member_level"`
	Status      int16       `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.Username,
		arg.Phone,
		arg.Nickname,
		arg.MemberLevel,
		arg.Status,
	)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id, card_no, card_name, face_value, user_id, order_no, status, valid_days, activated_at, expire_at, created_at, updated_at FROM t_free_card WHERE card_no = $1
`

func (q *Queries) GetCard(ctx context.Context, cardNo string) (TFreeCard, error) {
	row := q.db.QueryRow(ctx, getCard, cardNo)
	var i TFreeCard
	err := row.Scan(
		&i.ID,
		&i.CardNo,
		&i.CardName,
		&i.FaceValue,
		&i.UserID,
		&i.OrderNo,
		&i.Status,
		&i.ValidDays,
		&i.ActivatedAt,
		&i.ExpireAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, payment_no, order_no, user_id, pay_amount, pay_channel, pay_status, transaction_no, paid_at, created_at, updated_at FROM t_payment WHERE order_no = $1
`

func (q *Queries) GetPayment(ctx context.Context, orderNo string) (TPayment, error) {
	row := q.db.QueryRow(ctx, getPayment, orderNo)
	var i TPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderNo,
		&i.UserID,
		&i.PayAmount,
		&i.PayChannel,
		&i.PayStatus,
		&i.TransactionNo,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, phone, nickname, member_level, status, created_at, updated_at FROM t_user WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (TUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i TUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Phone,
		&i.Nickname,
		&i.MemberLevel,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCardsByUser = `-- name: ListCardsByUser :many
SELECT id, card_no, card_name, face_value, user_id, order_no, status, valid_days, activated_at, expire_at, created_at, updated_at FROM t_free_card
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCardsByUser(ctx context.Context, userID pgtype.Int8) ([]TFreeCard, error) {
	rows, err := q.db.Query(ctx, listCardsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TFreeCard{}
	for rows.Next() {
		var i TFreeCard
		if err := rows.Scan(
			&i.ID,
			&i.CardNo,
			&i.CardName,
			&i.FaceValue,
			&i.UserID,
			&i.OrderNo,
			&i.Status,
			&i.ValidDays,
			&i.ActivatedAt,
			&i.ExpireAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE t_payment
SET pay_status = $2, transaction_no = $3, paid_at = $4, updated_at = NOW()
WHERE payment_no = $1
`

type UpdatePaymentStatusParams struct {
	PaymentNo     string             `json:"payment_no"`
	PayStatus     int16              `json:"pay_status"`
	TransactionNo pgtype.Text        `json:"transaction_no"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentStatus,
		arg.PaymentNo,
		arg.PayStatus,
		arg.TransactionNo,
		arg.PaidAt,
	)
	return err
}
