// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/order_sync/v1/order_sync.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	v11 "seckill-api/common/v1"
	v1 "seckill-api/order/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncOrder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderNo        string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderSource    string                 `protobuf:"bytes,3,opt,name=order_source,json=orderSource,proto3" json:"order_source,omitempty"`
	TotalAmount    int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,5,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	PayAmount      int64                  `protobuf:"varint,6,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	TransactionNo  string                 `protobuf:"bytes,8,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncOrder) Reset() {
	*x = SyncOrder{}
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOrder) ProtoMessage() {}

func (x *SyncOrder) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOrder.ProtoReflect.Descriptor instead.
func (*SyncOrder) Descriptor() ([]byte, []int) {
	return file_api_order_sync_v1_order_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncOrder) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *SyncOrder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SyncOrder) GetOrderSource() string {
	if x != nil {
		return x.OrderSource
	}
	return ""
}

func (x *SyncOrder) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *SyncOrder) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *SyncOrder) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *SyncOrder) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *SyncOrder) GetTransactionNo() string {
	if x != nil {
		return x.TransactionNo
	}
	return ""
}

type SyncedOrder struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderNo        string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderSource    string                 `protobuf:"bytes,3,opt,name=order_source,json=orderSource,proto3" json:"order_source,omitempty"`
	TotalAmount    int64                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,5,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	PayAmount      int64                  `protobuf:"varint,6,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	OrderStatus    int64                  `protobuf:"varint,7,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	TransactionNo  string                 `protobuf:"bytes,10,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncedOrder) Reset() {
	*x = SyncedOrder{}
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncedOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncedOrder) ProtoMessage() {}

func (x *SyncedOrder) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncedOrder.ProtoReflect.Descriptor instead.
func (*SyncedOrder) Descriptor() ([]byte, []int) {
	return file_api_order_sync_v1_order_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncedOrder) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *SyncedOrder) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SyncedOrder) GetOrderSource() string {
	if x != nil {
		return x.OrderSource
	}
	return ""
}

func (x *SyncedOrder) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *SyncedOrder) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *SyncedOrder) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *SyncedOrder) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *SyncedOrder) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *SyncedOrder) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *SyncedOrder) GetTransactionNo() string {
	if x != nil {
		return x.TransactionNo
	}
	return ""
}

func (x *SyncedOrder) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SyncOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *SyncOrder             `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncOrderRequest) Reset() {
	*x = SyncOrderRequest{}
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncOrderRequest) ProtoMessage() {}

func (x *SyncOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncOrderRequest.ProtoReflect.Descriptor instead.
func (*SyncOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_order_sync_v1_order_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SyncOrderRequest) GetRequest() *SyncOrder {
	if x != nil {
		return x.Request
	}
	return nil
}

type SyncedOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *SyncedOrder           `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncedOrderResponse) Reset() {
	*x = SyncedOrderResponse{}
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncedOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncedOrderResponse) ProtoMessage() {}

func (x *SyncedOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncedOrderResponse.ProtoReflect.Descriptor instead.
func (*SyncedOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_sync_v1_order_sync_proto_rawDescGZIP(), []int{3}
}

func (x *SyncedOrderResponse) GetOrder() *SyncedOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

type SyncedOrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*SyncedOrder         `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncedOrderListResponse) Reset() {
	*x = SyncedOrderListResponse{}
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncedOrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncedOrderListResponse) ProtoMessage() {}

func (x *SyncedOrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_sync_v1_order_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncedOrderListResponse.ProtoReflect.Descriptor instead.
func (*SyncedOrderListResponse) Descriptor() ([]byte, []int) {
	return file_api_order_sync_v1_order_sync_proto_rawDescGZIP(), []int{4}
}

func (x *SyncedOrderListResponse) GetOrders() []*SyncedOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_api_order_sync_v1_order_sync_proto protoreflect.FileDescriptor

const file_api_order_sync_v1_order_sync_proto_rawDesc = "" +
	"\n" +
	"\"api/order_sync/v1/order_sync.proto\x12\x16seckill.api.order_sync\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aapi/common/v1/common.proto\x1a\x18api/order/v1/order.proto\"\xa9\x02\n" +
	"\tSyncOrder\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\forder_source\x18\x03 \x01(\tR\vorderSource\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\x12'\n" +
	"\x0fdiscount_amount\x18\x05 \x01(\x03R\x0ediscountAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x06 \x01(\x03R\tpayAmount\x123\n" +
	"\apaid_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x12%\n" +
	"\x0etransaction_no\x18\b \x01(\tR\rtransactionNo\"\xc8\x03\n" +
	"\vSyncedOrder\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\forder_source\x18\x03 \x01(\tR\vorderSource\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x03R\vtotalAmount\x12'\n" +
	"\x0fdiscount_amount\x18\x05 \x01(\x03R\x0ediscountAmount\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x06 \x01(\x03R\tpayAmount\x12!\n" +
	"\forder_status\x18\a \x01(\x03R\vorderStatus\x123\n" +
	"\apaid_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12%\n" +
	"\x0etransaction_no\x18\n" +
	" \x01(\tR\rtransactionNo\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"O\n" +
	"\x10SyncOrderRequest\x12;\n" +
	"\arequest\x18\x01 \x01(\v2!.seckill.api.order_sync.SyncOrderR\arequest\"P\n" +
	"\x13SyncedOrderResponse\x129\n" +
	"\x05order\x18\x01 \x01(\v2#.seckill.api.order_sync.SyncedOrderR\x05order\"V\n" +
	"\x17SyncedOrderListResponse\x12;\n" +
	"\x06orders\x18\x01 \x03(\v2#.seckill.api.order_sync.SyncedOrderR\x06orders2\x9e\x03\n" +
	"\x10OrderSyncService\x12M\n" +
	"\tSyncOrder\x12(.seckill.api.order_sync.SyncOrderRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\x0eGetSyncedOrder\x12!.seckill.api.order.OrderNoRequest\x1a+.seckill.api.order_sync.SyncedOrderResponse\x12q\n" +
	"\x1aListSyncedOrdersByOrderNos\x12\".seckill.api.order.OrderNosRequest\x1a/.seckill.api.order_sync.SyncedOrderListResponse\x12f\n" +
	"\x10ListSyncedOrders\x12!.seckill.api.common.UserIDRequest\x1a/.seckill.api.order_sync.SyncedOrderListResponseB\x1eZ\x1cseckill-api/order_sync/v1;v1b\x06proto3"

var (
	file_api_order_sync_v1_order_sync_proto_rawDescOnce sync.Once
	file_api_order_sync_v1_order_sync_proto_rawDescData []byte
)

func file_api_order_sync_v1_order_sync_proto_rawDescGZIP() []byte {
	file_api_order_sync_v1_order_sync_proto_rawDescOnce.Do(func() {
		file_api_order_sync_v1_order_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_sync_v1_order_sync_proto_rawDesc), len(file_api_order_sync_v1_order_sync_proto_rawDesc)))
	})
	return file_api_order_sync_v1_order_sync_proto_rawDescData
}

var file_api_order_sync_v1_order_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_order_sync_v1_order_sync_proto_goTypes = []any{
	(*SyncOrder)(nil),               // 0: seckill.api.order_sync.SyncOrder
	(*SyncedOrder)(nil),             // 1: seckill.api.order_sync.SyncedOrder
	(*SyncOrderRequest)(nil),        // 2: seckill.api.order_sync.SyncOrderRequest
	(*SyncedOrderResponse)(nil),     // 3: seckill.api.order_sync.SyncedOrderResponse
	(*SyncedOrderListResponse)(nil), // 4: seckill.api.order_sync.SyncedOrderListResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
	(*v1.OrderNoRequest)(nil),       // 6: seckill.api.order.OrderNoRequest
	(*v1.OrderNosRequest)(nil),      // 7: seckill.api.order.OrderNosRequest
	(*v11.UserIDRequest)(nil),       // 8: seckill.api.common.UserIDRequest
	(*emptypb.Empty)(nil),           // 9: google.protobuf.Empty
}
var file_api_order_sync_v1_order_sync_proto_depIdxs = []int32{
	5,  // 0: seckill.api.order_sync.SyncOrder.paid_at:type_name -> google.protobuf.Timestamp
	5,  // 1: seckill.api.order_sync.SyncedOrder.paid_at:type_name -> google.protobuf.Timestamp
	5,  // 2: seckill.api.order_sync.SyncedOrder.completed_at:type_name -> google.protobuf.Timestamp
	5,  // 3: seckill.api.order_sync.SyncedOrder.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: seckill.api.order_sync.SyncOrderRequest.request:type_name -> seckill.api.order_sync.SyncOrder
	1,  // 5: seckill.api.order_sync.SyncedOrderResponse.order:type_name -> seckill.api.order_sync.SyncedOrder
	1,  // 6: seckill.api.order_sync.SyncedOrderListResponse.orders:type_name -> seckill.api.order_sync.SyncedOrder
	2,  // 7: seckill.api.order_sync.OrderSyncService.SyncOrder:input_type -> seckill.api.order_sync.SyncOrderRequest
	6,  // 8: seckill.api.order_sync.OrderSyncService.GetSyncedOrder:input_type -> seckill.api.order.OrderNoRequest
	7,  // 9: seckill.api.order_sync.OrderSyncService.ListSyncedOrdersByOrderNos:input_type -> seckill.api.order.OrderNosRequest
	8,  // 10: seckill.api.order_sync.OrderSyncService.ListSyncedOrders:input_type -> seckill.api.common.UserIDRequest
	9,  // 11: seckill.api.order_sync.OrderSyncService.SyncOrder:output_type -> google.protobuf.Empty
	3,  // 12: seckill.api.order_sync.OrderSyncService.GetSyncedOrder:output_type -> seckill.api.order_sync.SyncedOrderResponse
	4,  // 13: seckill.api.order_sync.OrderSyncService.ListSyncedOrdersByOrderNos:output_type -> seckill.api.order_sync.SyncedOrderListResponse
	4,  // 14: seckill.api.order_sync.OrderSyncService.ListSyncedOrders:output_type -> seckill.api.order_sync.SyncedOrderListResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_order_sync_v1_order_sync_proto_init() }
func file_api_order_sync_v1_order_sync_proto_init() {
	if File_api_order_sync_v1_order_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_sync_v1_order_sync_proto_rawDesc), len(file_api_order_sync_v1_order_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_sync_v1_order_sync_proto_goTypes,
		DependencyIndexes: file_api_order_sync_v1_order_sync_proto_depIdxs,
		MessageInfos:      file_api_order_sync_v1_order_sync_proto_msgTypes,
	}.Build()
	File_api_order_sync_v1_order_sync_proto = out.File
	file_api_order_sync_v1_order_sync_proto_goTypes = nil
	file_api_order_sync_v1_order_sync_proto_depIdxs = nil
}
