// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/order_sync/v1/order_sync.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v11 "seckill-api/common/v1"
	v1 "seckill-api/order/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderSyncService_SyncOrder_FullMethodName                  = "/seckill.api.order_sync.OrderSyncService/SyncOrder"
	OrderSyncService_GetSyncedOrder_FullMethodName             = "/seckill.api.order_sync.OrderSyncService/GetSyncedOrder"
	OrderSyncService_ListSyncedOrdersByOrderNos_FullMethodName = "/seckill.api.order_sync.OrderSyncService/ListSyncedOrdersByOrderNos"
	OrderSyncService_ListSyncedOrders_FullMethodName           = "/seckill.api.order_sync.OrderSyncService/ListSyncedOrders"
)

// OrderSyncServiceClient is the client API for OrderSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderSyncServiceClient interface {
	SyncOrder(ctx context.Context, in *SyncOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSyncedOrder(ctx context.Context, in *v1.OrderNoRequest, opts ...grpc.CallOption) (*SyncedOrderResponse, error)
	ListSyncedOrdersByOrderNos(ctx context.Context, in *v1.OrderNosRequest, opts ...grpc.CallOption) (*SyncedOrderListResponse, error)
	ListSyncedOrders(ctx context.Context, in *v11.UserIDRequest, opts ...grpc.CallOption) (*SyncedOrderListResponse, error)
}

type orderSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderSyncServiceClient(cc grpc.ClientConnInterface) OrderSyncServiceClient {
	return &orderSyncServiceClient{cc}
}

func (c *orderSyncServiceClient) SyncOrder(ctx context.Context, in *SyncOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrderSyncService_SyncOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSyncServiceClient) GetSyncedOrder(ctx context.Context, in *v1.OrderNoRequest, opts ...grpc.CallOption) (*SyncedOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncedOrderResponse)
	err := c.cc.Invoke(ctx, OrderSyncService_GetSyncedOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSyncServiceClient) ListSyncedOrdersByOrderNos(ctx context.Context, in *v1.OrderNosRequest, opts ...grpc.CallOption) (*SyncedOrderListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncedOrderListResponse)
	err := c.cc.Invoke(ctx, OrderSyncService_ListSyncedOrdersByOrderNos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderSyncServiceClient) ListSyncedOrders(ctx context.Context, in *v11.UserIDRequest, opts ...grpc.CallOption) (*SyncedOrderListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncedOrderListResponse)
	err := c.cc.Invoke(ctx, OrderSyncService_ListSyncedOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderSyncServiceServer is the server API for OrderSyncService service.
// All implementations must embed UnimplementedOrderSyncServiceServer
// for forward compatibility.
type OrderSyncServiceServer interface {
	SyncOrder(context.Context, *SyncOrderRequest) (*emptypb.Empty, error)
	GetSyncedOrder(context.Context, *v1.OrderNoRequest) (*SyncedOrderResponse, error)
	ListSyncedOrdersByOrderNos(context.Context, *v1.OrderNosRequest) (*SyncedOrderListResponse, error)
	ListSyncedOrders(context.Context, *v11.UserIDRequest) (*SyncedOrderListResponse, error)
	mustEmbedUnimplementedOrderSyncServiceServer()
}

// UnimplementedOrderSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderSyncServiceServer struct{}

func (UnimplementedOrderSyncServiceServer) SyncOrder(context.Context, *SyncOrderRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncOrder not implemented")
}
func (UnimplementedOrderSyncServiceServer) GetSyncedOrder(context.Context, *v1.OrderNoRequest) (*SyncedOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncedOrder not implemented")
}
func (UnimplementedOrderSyncServiceServer) ListSyncedOrdersByOrderNos(context.Context, *v1.OrderNosRequest) (*SyncedOrderListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSyncedOrdersByOrderNos not implemented")
}
func (UnimplementedOrderSyncServiceServer) ListSyncedOrders(context.Context, *v11.UserIDRequest) (*SyncedOrderListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSyncedOrders not implemented")
}
func (UnimplementedOrderSyncServiceServer) mustEmbedUnimplementedOrderSyncServiceServer() {}
func (UnimplementedOrderSyncServiceServer) testEmbeddedByValue()                          {}

// UnsafeOrderSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderSyncServiceServer will
// result in compilation errors.
type UnsafeOrderSyncServiceServer interface {
	mustEmbedUnimplementedOrderSyncServiceServer()
}

func RegisterOrderSyncServiceServer(s grpc.ServiceRegistrar, srv OrderSyncServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderSyncService_ServiceDesc, srv)
}

func _OrderSyncService_SyncOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSyncServiceServer).SyncOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderSyncService_SyncOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSyncServiceServer).SyncOrder(ctx, req.(*SyncOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSyncService_GetSyncedOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.OrderNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSyncServiceServer).GetSyncedOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderSyncService_GetSyncedOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSyncServiceServer).GetSyncedOrder(ctx, req.(*v1.OrderNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSyncService_ListSyncedOrdersByOrderNos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.OrderNosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSyncServiceServer).ListSyncedOrdersByOrderNos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderSyncService_ListSyncedOrdersByOrderNos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSyncServiceServer).ListSyncedOrdersByOrderNos(ctx, req.(*v1.OrderNosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderSyncService_ListSyncedOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSyncServiceServer).ListSyncedOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderSyncService_ListSyncedOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSyncServiceServer).ListSyncedOrders(ctx, req.(*v11.UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderSyncService_ServiceDesc is the grpc.ServiceDesc for OrderSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.api.order_sync.OrderSyncService",
	HandlerType: (*OrderSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncOrder",
			Handler:    _OrderSyncService_SyncOrder_Handler,
		},
		{
			MethodName: "GetSyncedOrder",
			Handler:    _OrderSyncService_GetSyncedOrder_Handler,
		},
		{
			MethodName: "ListSyncedOrdersByOrderNos",
			Handler:    _OrderSyncService_ListSyncedOrdersByOrderNos_Handler,
		},
		{
			MethodName: "ListSyncedOrders",
			Handler:    _OrderSyncService_ListSyncedOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/order_sync/v1/order_sync.proto",
}
