// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/free_card/v1/free_card.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v1 "seckill-api/common/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FreeCardService_IssueCard_FullMethodName    = "/seckill.api.free_card.FreeCardService/IssueCard"
	FreeCardService_GetCard_FullMethodName      = "/seckill.api.free_card.FreeCardService/GetCard"
	FreeCardService_ListCards_FullMethodName    = "/seckill.api.free_card.FreeCardService/ListCards"
	FreeCardService_ActivateCard_FullMethodName = "/seckill.api.free_card.FreeCardService/ActivateCard"
	FreeCardService_FreezeCard_FullMethodName   = "/seckill.api.free_card.FreeCardService/FreezeCard"
	FreeCardService_UnfreezeCard_FullMethodName = "/seckill.api.free_card.FreeCardService/UnfreezeCard"
)

// FreeCardServiceClient is the client API for FreeCardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FreeCardServiceClient interface {
	IssueCard(ctx context.Context, in *IssueCardRequest, opts ...grpc.CallOption) (*CardNoResponse, error)
	GetCard(ctx context.Context, in *CardNoRequest, opts ...grpc.CallOption) (*FreeCardResponse, error)
	ListCards(ctx context.Context, in *v1.UserIDRequest, opts ...grpc.CallOption) (*FreeCardListResponse, error)
	ActivateCard(ctx context.Context, in *ActivateCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FreezeCard(ctx context.Context, in *CardNoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnfreezeCard(ctx context.Context, in *CardNoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type freeCardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFreeCardServiceClient(cc grpc.ClientConnInterface) FreeCardServiceClient {
	return &freeCardServiceClient{cc}
}

func (c *freeCardServiceClient) IssueCard(ctx context.Context, in *IssueCardRequest, opts ...grpc.CallOption) (*CardNoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CardNoResponse)
	err := c.cc.Invoke(ctx, FreeCardService_IssueCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeCardServiceClient) GetCard(ctx context.Context, in *CardNoRequest, opts ...grpc.CallOption) (*FreeCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreeCardResponse)
	err := c.cc.Invoke(ctx, FreeCardService_GetCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeCardServiceClient) ListCards(ctx context.Context, in *v1.UserIDRequest, opts ...grpc.CallOption) (*FreeCardListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreeCardListResponse)
	err := c.cc.Invoke(ctx, FreeCardService_ListCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeCardServiceClient) ActivateCard(ctx context.Context, in *ActivateCardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FreeCardService_ActivateCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeCardServiceClient) FreezeCard(ctx context.Context, in *CardNoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FreeCardService_FreezeCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *freeCardServiceClient) UnfreezeCard(ctx context.Context, in *CardNoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FreeCardService_UnfreezeCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FreeCardServiceServer is the server API for FreeCardService service.
// All implementations must embed UnimplementedFreeCardServiceServer
// for forward compatibility.
type FreeCardServiceServer interface {
	IssueCard(context.Context, *IssueCardRequest) (*CardNoResponse, error)
	GetCard(context.Context, *CardNoRequest) (*FreeCardResponse, error)
	ListCards(context.Context, *v1.UserIDRequest) (*FreeCardListResponse, error)
	ActivateCard(context.Context, *ActivateCardRequest) (*emptypb.Empty, error)
	FreezeCard(context.Context, *CardNoRequest) (*emptypb.Empty, error)
	UnfreezeCard(context.Context, *CardNoRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedFreeCardServiceServer()
}

// UnimplementedFreeCardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFreeCardServiceServer struct{}

func (UnimplementedFreeCardServiceServer) IssueCard(context.Context, *IssueCardRequest) (*CardNoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueCard not implemented")
}
func (UnimplementedFreeCardServiceServer) GetCard(context.Context, *CardNoRequest) (*FreeCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedFreeCardServiceServer) ListCards(context.Context, *v1.UserIDRequest) (*FreeCardListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCards not implemented")
}
func (UnimplementedFreeCardServiceServer) ActivateCard(context.Context, *ActivateCardRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateCard not implemented")
}
func (UnimplementedFreeCardServiceServer) FreezeCard(context.Context, *CardNoRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method FreezeCard not implemented")
}
func (UnimplementedFreeCardServiceServer) UnfreezeCard(context.Context, *CardNoRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfreezeCard not implemented")
}
func (UnimplementedFreeCardServiceServer) mustEmbedUnimplementedFreeCardServiceServer() {}
func (UnimplementedFreeCardServiceServer) testEmbeddedByValue()                         {}

// UnsafeFreeCardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FreeCardServiceServer will
// result in compilation errors.
type UnsafeFreeCardServiceServer interface {
	mustEmbedUnimplementedFreeCardServiceServer()
}

func RegisterFreeCardServiceServer(s grpc.ServiceRegistrar, srv FreeCardServiceServer) {
	// If the following call panics, it indicates UnimplementedFreeCardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FreeCardService_ServiceDesc, srv)
}

func _FreeCardService_IssueCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeCardServiceServer).IssueCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreeCardService_IssueCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeCardServiceServer).IssueCard(ctx, req.(*IssueCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreeCardService_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeCardServiceServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreeCardService_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeCardServiceServer).GetCard(ctx, req.(*CardNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreeCardService_ListCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.UserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeCardServiceServer).ListCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreeCardService_ListCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeCardServiceServer).ListCards(ctx, req.(*v1.UserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreeCardService_ActivateCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeCardServiceServer).ActivateCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreeCardService_ActivateCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeCardServiceServer).ActivateCard(ctx, req.(*ActivateCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreeCardService_FreezeCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeCardServiceServer).FreezeCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreeCardService_FreezeCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeCardServiceServer).FreezeCard(ctx, req.(*CardNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FreeCardService_UnfreezeCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CardNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FreeCardServiceServer).UnfreezeCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FreeCardService_UnfreezeCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FreeCardServiceServer).UnfreezeCard(ctx, req.(*CardNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FreeCardService_ServiceDesc is the grpc.ServiceDesc for FreeCardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FreeCardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.api.free_card.FreeCardService",
	HandlerType: (*FreeCardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCard",
			Handler:    _FreeCardService_IssueCard_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _FreeCardService_GetCard_Handler,
		},
		{
			MethodName: "ListCards",
			Handler:    _FreeCardService_ListCards_Handler,
		},
		{
			MethodName: "ActivateCard",
			Handler:    _FreeCardService_ActivateCard_Handler,
		},
		{
			MethodName: "FreezeCard",
			Handler:    _FreeCardService_FreezeCard_Handler,
		},
		{
			MethodName: "UnfreezeCard",
			Handler:    _FreeCardService_UnfreezeCard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/free_card/v1/free_card.proto",
}
