// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/free_card/v1/free_card.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	v1 "seckill-api/common/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	CardName      string                 `protobuf:"bytes,3,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	FaceValue     int64                  `protobuf:"varint,4,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	ValidDays     int64                  `protobuf:"varint,5,opt,name=valid_days,json=validDays,proto3" json:"valid_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCard) Reset() {
	*x = IssueCard{}
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCard) ProtoMessage() {}

func (x *IssueCard) ProtoReflect() protoreflect.Message {
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCard.ProtoReflect.Descriptor instead.
func (*IssueCard) Descriptor() ([]byte, []int) {
	return file_api_free_card_v1_free_card_proto_rawDescGZIP(), []int{0}
}

func (x *IssueCard) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IssueCard) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *IssueCard) GetCardName() string {
	if x != nil {
		return x.CardName
	}
	return ""
}

func (x *IssueCard) GetFaceValue() int64 {
	if x != nil {
		return x.FaceValue
	}
	return 0
}

func (x *IssueCard) GetValidDays() int64 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

type FreeCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNo        string                 `protobuf:"bytes,1,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	CardName      string                 `protobuf:"bytes,2,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	FaceValue     int64                  `protobuf:"varint,3,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,5,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	ValidDays     int64                  `protobuf:"varint,7,opt,name=valid_days,json=validDays,proto3" json:"valid_days,omitempty"`
	ActivatedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=activated_at,json=activatedAt,proto3" json:"activated_at,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeCard) Reset() {
	*x = FreeCard{}
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeCard) ProtoMessage() {}

func (x *FreeCard) ProtoReflect() protoreflect.Message {
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeCard.ProtoReflect.Descriptor instead.
func (*FreeCard) Descriptor() ([]byte, []int) {
	return file_api_free_card_v1_free_card_proto_rawDescGZIP(), []int{1}
}

func (x *FreeCard) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *FreeCard) GetCardName() string {
	if x != nil {
		return x.CardName
	}
	return ""
}

func (x *FreeCard) GetFaceValue() int64 {
	if x != nil {
		return x.FaceValue
	}
	return 0
}

func (x *FreeCard) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FreeCard) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *FreeCard) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FreeCard) GetValidDays() int64 {
	if x != nil {
		return x.ValidDays
	}
	return 0
}

func (x *FreeCard) GetActivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivatedAt
	}
	return nil
}

func (x *FreeCard) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

func (x *FreeCard) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type IssueCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *IssueCard             `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCardRequest) Reset() {
	*x = IssueCardRequest{}
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCardRequest) ProtoMessage() {}

func (x *IssueCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCardRequest.ProtoReflect.Descriptor instead.
func (*IssueCardRequest) Descriptor() ([]byte, []int) {
	return file_api_free_card_v1_free_card_proto_rawDescGZIP(), []int{2}
}

func (x *IssueCardRequest) GetRequest() *IssueCard {
	if x != nil {
		return x.Request
	}
	return nil
}

type ActivateCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNo        string                 `protobuf:"bytes,1,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateCardRequest) Reset() {
	*x = ActivateCardRequest{}
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateCardRequest) ProtoMessage() {}

func (x *ActivateCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateCardRequest.ProtoReflect.Descriptor instead.
func (*ActivateCardRequest) Descriptor() ([]byte, []int) {
	return file_api_free_card_v1_free_card_proto_rawDescGZIP(), []int{3}
}

func (x *ActivateCardRequest) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

func (x *ActivateCardRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ActivateCardRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type CardNoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNo        string                 `protobuf:"bytes,1,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardNoRequest) Reset() {
	*x = CardNoRequest{}
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardNoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardNoRequest) ProtoMessage() {}

func (x *CardNoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardNoRequest.ProtoReflect.Descriptor instead.
func (*CardNoRequest) Descriptor() ([]byte, []int) {
	return file_api_free_card_v1_free_card_proto_rawDescGZIP(), []int{4}
}

func (x *CardNoRequest) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

type CardNoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNo        string                 `protobuf:"bytes,1,opt,name=card_no,json=cardNo,proto3" json:"card_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardNoResponse) Reset() {
	*x = CardNoResponse{}
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardNoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardNoResponse) ProtoMessage() {}

func (x *CardNoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardNoResponse.ProtoReflect.Descriptor instead.
func (*CardNoResponse) Descriptor() ([]byte, []int) {
	return file_api_free_card_v1_free_card_proto_rawDescGZIP(), []int{5}
}

func (x *CardNoResponse) GetCardNo() string {
	if x != nil {
		return x.CardNo
	}
	return ""
}

type FreeCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *FreeCard              `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeCardResponse) Reset() {
	*x = FreeCardResponse{}
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeCardResponse) ProtoMessage() {}

func (x *FreeCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeCardResponse.ProtoReflect.Descriptor instead.
func (*FreeCardResponse) Descriptor() ([]byte, []int) {
	return file_api_free_card_v1_free_card_proto_rawDescGZIP(), []int{6}
}

func (x *FreeCardResponse) GetCard() *FreeCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type FreeCardListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*FreeCard            `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeCardListResponse) Reset() {
	*x = FreeCardListResponse{}
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeCardListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeCardListResponse) ProtoMessage() {}

func (x *FreeCardListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_free_card_v1_free_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeCardListResponse.ProtoReflect.Descriptor instead.
func (*FreeCardListResponse) Descriptor() ([]byte, []int) {
	return file_api_free_card_v1_free_card_proto_rawDescGZIP(), []int{7}
}

func (x *FreeCardListResponse) GetCards() []*FreeCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_api_free_card_v1_free_card_proto protoreflect.FileDescriptor

const file_api_free_card_v1_free_card_proto_rawDesc = "" +
	"\n" +
	" api/free_card/v1/free_card.proto\x12\x15seckill.api.free_card\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aapi/common/v1/common.proto\"\x9a\x01\n" +
	"\tIssueCard\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1b\n" +
	"\tcard_name\x18\x03 \x01(\tR\bcardName\x12\x1d\n" +
	"\n" +
	"face_value\x18\x04 \x01(\x03R\tfaceValue\x12\x1d\n" +
	"\n" +
	"valid_days\x18\x05 \x01(\x03R\tvalidDays\"\xfd\x02\n" +
	"\bFreeCard\x12\x17\n" +
	"\acard_no\x18\x01 \x01(\tR\x06cardNo\x12\x1b\n" +
	"\tcard_name\x18\x02 \x01(\tR\bcardName\x12\x1d\n" +
	"\n" +
	"face_value\x18\x03 \x01(\x03R\tfaceValue\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x05 \x01(\tR\aorderNo\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x1d\n" +
	"\n" +
	"valid_days\x18\a \x01(\x03R\tvalidDays\x12=\n" +
	"\factivated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vactivatedAt\x127\n" +
	"\texpire_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"N\n" +
	"\x10IssueCardRequest\x12:\n" +
	"\arequest\x18\x01 \x01(\v2 .seckill.api.free_card.IssueCardR\arequest\"b\n" +
	"\x13ActivateCardRequest\x12\x17\n" +
	"\acard_no\x18\x01 \x01(\tR\x06cardNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\"(\n" +
	"\rCardNoRequest\x12\x17\n" +
	"\acard_no\x18\x01 \x01(\tR\x06cardNo\")\n" +
	"\x0eCardNoResponse\x12\x17\n" +
	"\acard_no\x18\x01 \x01(\tR\x06cardNo\"G\n" +
	"\x10FreeCardResponse\x123\n" +
	"\x04card\x18\x01 \x01(\v2\x1f.seckill.api.free_card.FreeCardR\x04card\"M\n" +
	"\x14FreeCardListResponse\x125\n" +
	"\x05cards\x18\x01 \x03(\v2\x1f.seckill.api.free_card.FreeCardR\x05cards2\x93\x04\n" +
	"\x0fFreeCardService\x12[\n" +
	"\tIssueCard\x12'.seckill.api.free_card.IssueCardRequest\x1a%.seckill.api.free_card.CardNoResponse\x12X\n" +
	"\aGetCard\x12$.seckill.api.free_card.CardNoRequest\x1a'.seckill.api.free_card.FreeCardResponse\x12[\n" +
	"\tListCards\x12!.seckill.api.common.UserIDRequest\x1a+.seckill.api.free_card.FreeCardListResponse\x12R\n" +
	"\fActivateCard\x12*.seckill.api.free_card.ActivateCardRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\n" +
	"FreezeCard\x12$.seckill.api.free_card.CardNoRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\fUnfreezeCard\x12$.seckill.api.free_card.CardNoRequest\x1a\x16.google.protobuf.EmptyB\x1dZ\x1bseckill-api/free_card/v1;v1b\x06proto3"

var (
	file_api_free_card_v1_free_card_proto_rawDescOnce sync.Once
	file_api_free_card_v1_free_card_proto_rawDescData []byte
)

func file_api_free_card_v1_free_card_proto_rawDescGZIP() []byte {
	file_api_free_card_v1_free_card_proto_rawDescOnce.Do(func() {
		file_api_free_card_v1_free_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_free_card_v1_free_card_proto_rawDesc), len(file_api_free_card_v1_free_card_proto_rawDesc)))
	})
	return file_api_free_card_v1_free_card_proto_rawDescData
}

var file_api_free_card_v1_free_card_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_free_card_v1_free_card_proto_goTypes = []any{
	(*IssueCard)(nil),             // 0: seckill.api.free_card.IssueCard
	(*FreeCard)(nil),              // 1: seckill.api.free_card.FreeCard
	(*IssueCardRequest)(nil),      // 2: seckill.api.free_card.IssueCardRequest
	(*ActivateCardRequest)(nil),   // 3: seckill.api.free_card.ActivateCardRequest
	(*CardNoRequest)(nil),         // 4: seckill.api.free_card.CardNoRequest
	(*CardNoResponse)(nil),        // 5: seckill.api.free_card.CardNoResponse
	(*FreeCardResponse)(nil),      // 6: seckill.api.free_card.FreeCardResponse
	(*FreeCardListResponse)(nil),  // 7: seckill.api.free_card.FreeCardListResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*v1.UserIDRequest)(nil),      // 9: seckill.api.common.UserIDRequest
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_api_free_card_v1_free_card_proto_depIdxs = []int32{
	8,  // 0: seckill.api.free_card.FreeCard.activated_at:type_name -> google.protobuf.Timestamp
	8,  // 1: seckill.api.free_card.FreeCard.expire_at:type_name -> google.protobuf.Timestamp
	8,  // 2: seckill.api.free_card.FreeCard.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: seckill.api.free_card.IssueCardRequest.request:type_name -> seckill.api.free_card.IssueCard
	1,  // 4: seckill.api.free_card.FreeCardResponse.card:type_name -> seckill.api.free_card.FreeCard
	1,  // 5: seckill.api.free_card.FreeCardListResponse.cards:type_name -> seckill.api.free_card.FreeCard
	2,  // 6: seckill.api.free_card.FreeCardService.IssueCard:input_type -> seckill.api.free_card.IssueCardRequest
	4,  // 7: seckill.api.free_card.FreeCardService.GetCard:input_type -> seckill.api.free_card.CardNoRequest
	9,  // 8: seckill.api.free_card.FreeCardService.ListCards:input_type -> seckill.api.common.UserIDRequest
	3,  // 9: seckill.api.free_card.FreeCardService.ActivateCard:input_type -> seckill.api.free_card.ActivateCardRequest
	4,  // 10: seckill.api.free_card.FreeCardService.FreezeCard:input_type -> seckill.api.free_card.CardNoRequest
	4,  // 11: seckill.api.free_card.FreeCardService.UnfreezeCard:input_type -> seckill.api.free_card.CardNoRequest
	5,  // 12: seckill.api.free_card.FreeCardService.IssueCard:output_type -> seckill.api.free_card.CardNoResponse
	6,  // 13: seckill.api.free_card.FreeCardService.GetCard:output_type -> seckill.api.free_card.FreeCardResponse
	7,  // 14: seckill.api.free_card.FreeCardService.ListCards:output_type -> seckill.api.free_card.FreeCardListResponse
	10, // 15: seckill.api.free_card.FreeCardService.ActivateCard:output_type -> google.protobuf.Empty
	10, // 16: seckill.api.free_card.FreeCardService.FreezeCard:output_type -> google.protobuf.Empty
	10, // 17: seckill.api.free_card.FreeCardService.UnfreezeCard:output_type -> google.protobuf.Empty
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_free_card_v1_free_card_proto_init() }
func file_api_free_card_v1_free_card_proto_init() {
	if File_api_free_card_v1_free_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_free_card_v1_free_card_proto_rawDesc), len(file_api_free_card_v1_free_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_free_card_v1_free_card_proto_goTypes,
		DependencyIndexes: file_api_free_card_v1_free_card_proto_depIdxs,
		MessageInfos:      file_api_free_card_v1_free_card_proto_msgTypes,
	}.Build()
	File_api_free_card_v1_free_card_proto = out.File
	file_api_free_card_v1_free_card_proto_goTypes = nil
	file_api_free_card_v1_free_card_proto_depIdxs = nil
}
