// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/order/v1/order.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderNo        string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityNo     string                 `protobuf:"bytes,3,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	SkuNo          string                 `protobuf:"bytes,4,opt,name=sku_no,json=skuNo,proto3" json:"sku_no,omitempty"`
	Quantity       int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PayAmount      int64                  `protobuf:"varint,6,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	Status         string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TraceId        string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TransactionNo  string                 `protobuf:"bytes,9,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	PaidAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	ClosedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RequestTraceId string                 `protobuf:"bytes,13,opt,name=request_trace_id,json=requestTraceId,proto3" json:"request_trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *Order) GetSkuNo() string {
	if x != nil {
		return x.SkuNo
	}
	return ""
}

func (x *Order) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Order) GetTransactionNo() string {
	if x != nil {
		return x.TransactionNo
	}
	return ""
}

func (x *Order) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *Order) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetRequestTraceId() string {
	if x != nil {
		return x.RequestTraceId
	}
	return ""
}

type OrderNoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderNoRequest) Reset() {
	*x = OrderNoRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderNoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderNoRequest) ProtoMessage() {}

func (x *OrderNoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderNoRequest.ProtoReflect.Descriptor instead.
func (*OrderNoRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderNoRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type OrderNosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNos      []string               `protobuf:"bytes,1,rep,name=order_nos,json=orderNos,proto3" json:"order_nos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderNosRequest) Reset() {
	*x = OrderNosRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderNosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderNosRequest) ProtoMessage() {}

func (x *OrderNosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderNosRequest.ProtoReflect.Descriptor instead.
func (*OrderNosRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderNosRequest) GetOrderNos() []string {
	if x != nil {
		return x.OrderNos
	}
	return nil
}

type OrderListByActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListByActivityRequest) Reset() {
	*x = OrderListByActivityRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListByActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListByActivityRequest) ProtoMessage() {}

func (x *OrderListByActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListByActivityRequest.ProtoReflect.Descriptor instead.
func (*OrderListByActivityRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderListByActivityRequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

type OrderListByActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNos   []string               `protobuf:"bytes,1,rep,name=activity_nos,json=activityNos,proto3" json:"activity_nos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListByActivitiesRequest) Reset() {
	*x = OrderListByActivitiesRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListByActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListByActivitiesRequest) ProtoMessage() {}

func (x *OrderListByActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListByActivitiesRequest.ProtoReflect.Descriptor instead.
func (*OrderListByActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderListByActivitiesRequest) GetActivityNos() []string {
	if x != nil {
		return x.ActivityNos
	}
	return nil
}

type OrderListByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListByUserRequest) Reset() {
	*x = OrderListByUserRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListByUserRequest) ProtoMessage() {}

func (x *OrderListByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListByUserRequest.ProtoReflect.Descriptor instead.
func (*OrderListByUserRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderListByUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type OrderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListResponse) Reset() {
	*x = OrderListResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListResponse) ProtoMessage() {}

func (x *OrderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListResponse.ProtoReflect.Descriptor instead.
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderListResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrdersByActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersByActivity) Reset() {
	*x = OrdersByActivity{}
	mi := &file_api_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersByActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersByActivity) ProtoMessage() {}

func (x *OrdersByActivity) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersByActivity.ProtoReflect.Descriptor instead.
func (*OrdersByActivity) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrdersByActivity) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *OrdersByActivity) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderListByActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OrdersByActivity    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListByActivitiesResponse) Reset() {
	*x = OrderListByActivitiesResponse{}
	mi := &file_api_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListByActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListByActivitiesResponse) ProtoMessage() {}

func (x *OrderListByActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListByActivitiesResponse.ProtoReflect.Descriptor instead.
func (*OrderListByActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *OrderListByActivitiesResponse) GetItems() []*OrdersByActivity {
	if x != nil {
		return x.Items
	}
	return nil
}

type MarkOrderPaidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TransactionNo string                 `protobuf:"bytes,2,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkOrderPaidRequest) Reset() {
	*x = MarkOrderPaidRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkOrderPaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkOrderPaidRequest) ProtoMessage() {}

func (x *MarkOrderPaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkOrderPaidRequest.ProtoReflect.Descriptor instead.
func (*MarkOrderPaidRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *MarkOrderPaidRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *MarkOrderPaidRequest) GetTransactionNo() string {
	if x != nil {
		return x.TransactionNo
	}
	return ""
}

func (x *MarkOrderPaidRequest) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

type GetOrderByUserAndTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderByUserAndTraceRequest) Reset() {
	*x = GetOrderByUserAndTraceRequest{}
	mi := &file_api_order_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderByUserAndTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderByUserAndTraceRequest) ProtoMessage() {}

func (x *GetOrderByUserAndTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_order_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderByUserAndTraceRequest.ProtoReflect.Descriptor instead.
func (*GetOrderByUserAndTraceRequest) Descriptor() ([]byte, []int) {
	return file_api_order_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderByUserAndTraceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderByUserAndTraceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_api_order_v1_order_proto protoreflect.FileDescriptor

const file_api_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x18api/order/v1/order.proto\x12\x11seckill.api.order\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x03\n" +
	"\x05Order\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vactivity_no\x18\x03 \x01(\tR\n" +
	"activityNo\x12\x15\n" +
	"\x06sku_no\x18\x04 \x01(\tR\x05skuNo\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x06 \x01(\x03R\tpayAmount\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12%\n" +
	"\x0etransaction_no\x18\t \x01(\tR\rtransactionNo\x123\n" +
	"\apaid_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x127\n" +
	"\tclosed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12(\n" +
	"\x10request_trace_id\x18\r \x01(\tR\x0erequestTraceId\"+\n" +
	"\x0eOrderNoRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\".\n" +
	"\x0fOrderNosRequest\x12\x1b\n" +
	"\torder_nos\x18\x01 \x03(\tR\borderNos\"=\n" +
	"\x1aOrderListByActivityRequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\"A\n" +
	"\x1cOrderListByActivitiesRequest\x12!\n" +
	"\factivity_nos\x18\x01 \x03(\tR\vactivityNos\"1\n" +
	"\x16OrderListByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"?\n" +
	"\rOrderResponse\x12.\n" +
	"\x05order\x18\x01 \x01(\v2\x18.seckill.api.order.OrderR\x05order\"E\n" +
	"\x11OrderListResponse\x120\n" +
	"\x06orders\x18\x01 \x03(\v2\x18.seckill.api.order.OrderR\x06orders\"e\n" +
	"\x10OrdersByActivity\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x120\n" +
	"\x06orders\x18\x02 \x03(\v2\x18.seckill.api.order.OrderR\x06orders\"Z\n" +
	"\x1dOrderListByActivitiesResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.seckill.api.order.OrdersByActivityR\x05items\"\x8d\x01\n" +
	"\x14MarkOrderPaidRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12%\n" +
	"\x0etransaction_no\x18\x02 \x01(\tR\rtransactionNo\x123\n" +
	"\apaid_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"S\n" +
	"\x1dGetOrderByUserAndTraceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId2\xfb\x05\n" +
	"\fOrderService\x12G\n" +
	"\vCreateOrder\x12 .seckill.api.order.OrderResponse\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\bGetOrder\x12!.seckill.api.order.OrderNoRequest\x1a .seckill.api.order.OrderResponse\x12l\n" +
	"\x16GetOrderByUserAndTrace\x120.seckill.api.order.GetOrderByUserAndTraceRequest\x1a .seckill.api.order.OrderResponse\x12k\n" +
	"\x14ListOrdersByActivity\x12-.seckill.api.order.OrderListByActivityRequest\x1a$.seckill.api.order.OrderListResponse\x12{\n" +
	"\x16ListOrdersByActivities\x12/.seckill.api.order.OrderListByActivitiesRequest\x1a0.seckill.api.order.OrderListByActivitiesResponse\x12c\n" +
	"\x10ListOrdersByUser\x12).seckill.api.order.OrderListByUserRequest\x1a$.seckill.api.order.OrderListResponse\x12K\n" +
	"\bMarkPaid\x12'.seckill.api.order.MarkOrderPaidRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\n" +
	"CloseOrder\x12!.seckill.api.order.OrderNoRequest\x1a\x16.google.protobuf.EmptyB\x19Z\x17seckill-api/order/v1;v1b\x06proto3"

var (
	file_api_order_v1_order_proto_rawDescOnce sync.Once
	file_api_order_v1_order_proto_rawDescData []byte
)

func file_api_order_v1_order_proto_rawDescGZIP() []byte {
	file_api_order_v1_order_proto_rawDescOnce.Do(func() {
		file_api_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)))
	})
	return file_api_order_v1_order_proto_rawDescData
}

var file_api_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_order_v1_order_proto_goTypes = []any{
	(*Order)(nil),                         // 0: seckill.api.order.Order
	(*OrderNoRequest)(nil),                // 1: seckill.api.order.OrderNoRequest
	(*OrderNosRequest)(nil),               // 2: seckill.api.order.OrderNosRequest
	(*OrderListByActivityRequest)(nil),    // 3: seckill.api.order.OrderListByActivityRequest
	(*OrderListByActivitiesRequest)(nil),  // 4: seckill.api.order.OrderListByActivitiesRequest
	(*OrderListByUserRequest)(nil),        // 5: seckill.api.order.OrderListByUserRequest
	(*OrderResponse)(nil),                 // 6: seckill.api.order.OrderResponse
	(*OrderListResponse)(nil),             // 7: seckill.api.order.OrderListResponse
	(*OrdersByActivity)(nil),              // 8: seckill.api.order.OrdersByActivity
	(*OrderListByActivitiesResponse)(nil), // 9: seckill.api.order.OrderListByActivitiesResponse
	(*MarkOrderPaidRequest)(nil),          // 10: seckill.api.order.MarkOrderPaidRequest
	(*GetOrderByUserAndTraceRequest)(nil), // 11: seckill.api.order.GetOrderByUserAndTraceRequest
	(*timestamppb.Timestamp)(nil),         // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 13: google.protobuf.Empty
}
var file_api_order_v1_order_proto_depIdxs = []int32{
	12, // 0: seckill.api.order.Order.paid_at:type_name -> google.protobuf.Timestamp
	12, // 1: seckill.api.order.Order.closed_at:type_name -> google.protobuf.Timestamp
	12, // 2: seckill.api.order.Order.created_at:type_name -> google.protobuf.Timestamp
	0,  // 3: seckill.api.order.OrderResponse.order:type_name -> seckill.api.order.Order
	0,  // 4: seckill.api.order.OrderListResponse.orders:type_name -> seckill.api.order.Order
	0,  // 5: seckill.api.order.OrdersByActivity.orders:type_name -> seckill.api.order.Order
	8,  // 6: seckill.api.order.OrderListByActivitiesResponse.items:type_name -> seckill.api.order.OrdersByActivity
	12, // 7: seckill.api.order.MarkOrderPaidRequest.paid_at:type_name -> google.protobuf.Timestamp
	6,  // 8: seckill.api.order.OrderService.CreateOrder:input_type -> seckill.api.order.OrderResponse
	1,  // 9: seckill.api.order.OrderService.GetOrder:input_type -> seckill.api.order.OrderNoRequest
	11, // 10: seckill.api.order.OrderService.GetOrderByUserAndTrace:input_type -> seckill.api.order.GetOrderByUserAndTraceRequest
	3,  // 11: seckill.api.order.OrderService.ListOrdersByActivity:input_type -> seckill.api.order.OrderListByActivityRequest
	4,  // 12: seckill.api.order.OrderService.ListOrdersByActivities:input_type -> seckill.api.order.OrderListByActivitiesRequest
	5,  // 13: seckill.api.order.OrderService.ListOrdersByUser:input_type -> seckill.api.order.OrderListByUserRequest
	10, // 14: seckill.api.order.OrderService.MarkPaid:input_type -> seckill.api.order.MarkOrderPaidRequest
	1,  // 15: seckill.api.order.OrderService.CloseOrder:input_type -> seckill.api.order.OrderNoRequest
	13, // 16: seckill.api.order.OrderService.CreateOrder:output_type -> google.protobuf.Empty
	6,  // 17: seckill.api.order.OrderService.GetOrder:output_type -> seckill.api.order.OrderResponse
	6,  // 18: seckill.api.order.OrderService.GetOrderByUserAndTrace:output_type -> seckill.api.order.OrderResponse
	7,  // 19: seckill.api.order.OrderService.ListOrdersByActivity:output_type -> seckill.api.order.OrderListResponse
	9,  // 20: seckill.api.order.OrderService.ListOrdersByActivities:output_type -> seckill.api.order.OrderListByActivitiesResponse
	7,  // 21: seckill.api.order.OrderService.ListOrdersByUser:output_type -> seckill.api.order.OrderListResponse
	13, // 22: seckill.api.order.OrderService.MarkPaid:output_type -> google.protobuf.Empty
	13, // 23: seckill.api.order.OrderService.CloseOrder:output_type -> google.protobuf.Empty
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_order_v1_order_proto_init() }
func file_api_order_v1_order_proto_init() {
	if File_api_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_order_v1_order_proto_rawDesc), len(file_api_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_order_v1_order_proto_goTypes,
		DependencyIndexes: file_api_order_v1_order_proto_depIdxs,
		MessageInfos:      file_api_order_v1_order_proto_msgTypes,
	}.Build()
	File_api_order_v1_order_proto = out.File
	file_api_order_v1_order_proto_goTypes = nil
	file_api_order_v1_order_proto_depIdxs = nil
}
