// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type SkOrder struct {
	ID             int64              `json:"id"`
	OrderNo        string             `json:"order_no"`
	UserID         int64              `json:"user_id"`
	ActivityNo     string             `json:"activity_no"`
	SkuNo          string             `json:"sku_no"`
	Quantity       int64              `json:"quantity"`
	TotalAmount    int64              `json:"total_amount"`
	DiscountAmount int64              `json:"discount_amount"`
	PayAmount      int64              `json:"pay_amount"`
	OrderStatus    string             `json:"order_status"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	TransactionNo  pgtype.Text        `json:"transaction_no"`
	TraceID        pgtype.Text        `json:"trace_id"`
	Remark         string             `json:"remark"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	IsDeleted      int16              `json:"is_deleted"`
}

type SkOrderItem struct {
	ID          int64     `json:"id"`
	OrderNo     string    `json:"order_no"`
	ActivityNo  string    `json:"activity_no"`
	SkuNo       string    `json:"sku_no"`
	ProductName string    `json:"product_name"`
	Quantity    int64     `json:"quantity"`
	Price       int64     `json:"price"`
	TotalAmount int64     `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsDeleted   int16     `json:"is_deleted"`
}

type SkOrderItemP0 struct {
	ID          int64     `json:"id"`
	OrderNo     string    `json:"order_no"`
	ActivityNo  string    `json:"activity_no"`
	SkuNo       string    `json:"sku_no"`
	ProductName string    `json:"product_name"`
	Quantity    int64     `json:"quantity"`
	Price       int64     `json:"price"`
	TotalAmount int64     `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsDeleted   int16     `json:"is_deleted"`
}

type SkOrderItemP1 struct {
	ID          int64     `json:"id"`
	OrderNo     string    `json:"order_no"`
	ActivityNo  string    `json:"activity_no"`
	SkuNo       string    `json:"sku_no"`
	ProductName string    `json:"product_name"`
	Quantity    int64     `json:"quantity"`
	Price       int64     `json:"price"`
	TotalAmount int64     `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsDeleted   int16     `json:"is_deleted"`
}

type SkOrderItemP2 struct {
	ID          int64     `json:"id"`
	OrderNo     string    `json:"order_no"`
	ActivityNo  string    `json:"activity_no"`
	SkuNo       string    `json:"sku_no"`
	ProductName string    `json:"product_name"`
	Quantity    int64     `json:"quantity"`
	Price       int64     `json:"price"`
	TotalAmount int64     `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsDeleted   int16     `json:"is_deleted"`
}

type SkOrderItemP3 struct {
	ID          int64     `json:"id"`
	OrderNo     string    `json:"order_no"`
	ActivityNo  string    `json:"activity_no"`
	SkuNo       string    `json:"sku_no"`
	ProductName string    `json:"product_name"`
	Quantity    int64     `json:"quantity"`
	Price       int64     `json:"price"`
	TotalAmount int64     `json:"total_amount"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsDeleted   int16     `json:"is_deleted"`
}

type SkOrderP0 struct {
	ID             int64              `json:"id"`
	OrderNo        string             `json:"order_no"`
	UserID         int64              `json:"user_id"`
	ActivityNo     string             `json:"activity_no"`
	SkuNo          string             `json:"sku_no"`
	Quantity       int64              `json:"quantity"`
	TotalAmount    int64              `json:"total_amount"`
	DiscountAmount int64              `json:"discount_amount"`
	PayAmount      int64              `json:"pay_amount"`
	OrderStatus    string             `json:"order_status"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	TransactionNo  pgtype.Text        `json:"transaction_no"`
	TraceID        pgtype.Text        `json:"trace_id"`
	Remark         string             `json:"remark"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	IsDeleted      int16              `json:"is_deleted"`
}

type SkOrderP1 struct {
	ID             int64              `json:"id"`
	OrderNo        string             `json:"order_no"`
	UserID         int64              `json:"user_id"`
	ActivityNo     string             `json:"activity_no"`
	SkuNo          string             `json:"sku_no"`
	Quantity       int64              `json:"quantity"`
	TotalAmount    int64              `json:"total_amount"`
	DiscountAmount int64              `json:"discount_amount"`
	PayAmount      int64              `json:"pay_amount"`
	OrderStatus    string             `json:"order_status"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	TransactionNo  pgtype.Text        `json:"transaction_no"`
	TraceID        pgtype.Text        `json:"trace_id"`
	Remark         string             `json:"remark"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	IsDeleted      int16              `json:"is_deleted"`
}

type SkOrderP2 struct {
	ID             int64              `json:"id"`
	OrderNo        string             `json:"order_no"`
	UserID         int64              `json:"user_id"`
	ActivityNo     string             `json:"activity_no"`
	SkuNo          string             `json:"sku_no"`
	Quantity       int64              `json:"quantity"`
	TotalAmount    int64              `json:"total_amount"`
	DiscountAmount int64              `json:"discount_amount"`
	PayAmount      int64              `json:"pay_amount"`
	OrderStatus    string             `json:"order_status"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	TransactionNo  pgtype.Text        `json:"transaction_no"`
	TraceID        pgtype.Text        `json:"trace_id"`
	Remark         string             `json:"remark"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	IsDeleted      int16              `json:"is_deleted"`
}

type SkOrderP3 struct {
	ID             int64              `json:"id"`
	OrderNo        string             `json:"order_no"`
	UserID         int64              `json:"user_id"`
	ActivityNo     string             `json:"activity_no"`
	SkuNo          string             `json:"sku_no"`
	Quantity       int64              `json:"quantity"`
	TotalAmount    int64              `json:"total_amount"`
	DiscountAmount int64              `json:"discount_amount"`
	PayAmount      int64              `json:"pay_amount"`
	OrderStatus    string             `json:"order_status"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	TransactionNo  pgtype.Text        `json:"transaction_no"`
	TraceID        pgtype.Text        `json:"trace_id"`
	Remark         string             `json:"remark"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	IsDeleted      int16              `json:"is_deleted"`
}
