// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeOrder = `-- name: CloseOrder :exec
UPDATE sk_order
SET order_status = 'CLOSED',
    closed_at = NOW(),
    updated_at = NOW()
WHERE order_no = $1 AND order_status = 'PENDING_PAY' AND is_deleted = 0
`

func (q *Queries) CloseOrder(ctx context.Context, orderNo string) error {
	_, err := q.db.Exec(ctx, closeOrder, orderNo)
	return err
}

const countOrdersByActivity = `-- name: CountOrdersByActivity :one
SELECT COUNT(*) FROM sk_order
WHERE activity_no = $1 AND is_deleted = 0
`

func (q *Queries) CountOrdersByActivity(ctx context.Context, activityNo string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByActivity, activityNo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO sk_order (
    order_no, user_id, activity_no, sku_no, quantity,
    total_amount, discount_amount, pay_amount, order_status,
    trace_id, remark
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11
)
`

type CreateOrderParams struct {
	OrderNo        string      `json:"order_no"`
	UserID         int64       `json:"user_id"`
	ActivityNo     string      `json:"activity_no"`
	SkuNo          string      `json:"sku_no"`
	Quantity       int64       `json:"quantity"`
	TotalAmount    int64       `json:"total_amount"`
	DiscountAmount int64       `json:"discount_amount"`
	PayAmount      int64       `json:"pay_amount"`
	OrderStatus    string      `json:"order_status"`
	TraceID        pgtype.Text `json:"trace_id"`
	Remark         string      `json:"remark"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.Exec(ctx, createOrder,
		arg.OrderNo,
		arg.UserID,
		arg.ActivityNo,
		arg.SkuNo,
		arg.Quantity,
		arg.TotalAmount,
		arg.DiscountAmount,
		arg.PayAmount,
		arg.OrderStatus,
		arg.TraceID,
		arg.Remark,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO sk_order_item (
    order_no, activity_no, sku_no, product_name,
    quantity, price, total_amount
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
`

type CreateOrderItemParams struct {
	OrderNo     string `json:"order_no"`
	ActivityNo  string `json:"activity_no"`
	SkuNo       string `json:"sku_no"`
	ProductName string `json:"product_name"`
	Quantity    int64  `json:"quantity"`
	Price       int64  `json:"price"`
	TotalAmount int64  `json:"total_amount"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.Exec(ctx, createOrderItem,
		arg.OrderNo,
		arg.ActivityNo,
		arg.SkuNo,
		arg.ProductName,
		arg.Quantity,
		arg.Price,
		arg.TotalAmount,
	)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, order_no, user_id, activity_no, sku_no, quantity, total_amount, discount_amount, pay_amount, order_status, paid_at, closed_at, transaction_no, trace_id, remark, created_at, updated_at, is_deleted FROM sk_order
WHERE order_no = $1 AND is_deleted = 0
`

func (q *Queries) GetOrder(ctx context.Context, orderNo string) (SkOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, orderNo)
	var i SkOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.ActivityNo,
		&i.SkuNo,
		&i.Quantity,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.PayAmount,
		&i.OrderStatus,
		&i.PaidAt,
		&i.ClosedAt,
		&i.TransactionNo,
		&i.TraceID,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getOrderByUserAndOrderNo = `-- name: GetOrderByUserAndOrderNo :one
SELECT id, order_no, user_id, activity_no, sku_no, quantity, total_amount, discount_amount, pay_amount, order_status, paid_at, closed_at, transaction_no, trace_id, remark, created_at, updated_at, is_deleted FROM sk_order
WHERE user_id = $1 AND order_no = $2 AND is_deleted = 0
`

type GetOrderByUserAndOrderNoParams struct {
	UserID  int64  `json:"user_id"`
	OrderNo string `json:"order_no"`
}

func (q *Queries) GetOrderByUserAndOrderNo(ctx context.Context, arg GetOrderByUserAndOrderNoParams) (SkOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByUserAndOrderNo, arg.UserID, arg.OrderNo)
	var i SkOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.ActivityNo,
		&i.SkuNo,
		&i.Quantity,
		&i.TotalAmount,
		&i.DiscountAmount,
		&i.PayAmount,
		&i.OrderStatus,
		&i.PaidAt,
		&i.ClosedAt,
		&i.TransactionNo,
		&i.TraceID,
		&i.Remark,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const listOrdersByActivities = `-- name: ListOrdersByActivities :many
SELECT id, order_no, user_id, activity_no, sku_no, quantity, total_amount, discount_amount, pay_amount, order_status, paid_at, closed_at, transaction_no, trace_id, remark, created_at, updated_at, is_deleted FROM sk_order
WHERE activity_no = ANY($1::varchar[])
  AND is_deleted = 0
  AND created_at > NOW() - INTERVAL '7 days'
ORDER BY created_at DESC
LIMIT 10000
`

func (q *Queries) ListOrdersByActivities(ctx context.Context, dollar_1 []string) ([]SkOrder, error) {
	rows, err := q.db.Query(ctx, listOrdersByActivities, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkOrder{}
	for rows.Next() {
		var i SkOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.ActivityNo,
			&i.SkuNo,
			&i.Quantity,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.PayAmount,
			&i.OrderStatus,
			&i.PaidAt,
			&i.ClosedAt,
			&i.TransactionNo,
			&i.TraceID,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByActivity = `-- name: ListOrdersByActivity :many
SELECT id, order_no, user_id, activity_no, sku_no, quantity, total_amount, discount_amount, pay_amount, order_status, paid_at, closed_at, transaction_no, trace_id, remark, created_at, updated_at, is_deleted FROM sk_order
WHERE activity_no = $1 AND is_deleted = 0
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByActivityParams struct {
	ActivityNo string `json:"activity_no"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListOrdersByActivity(ctx context.Context, arg ListOrdersByActivityParams) ([]SkOrder, error) {
	rows, err := q.db.Query(ctx, listOrdersByActivity, arg.ActivityNo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkOrder{}
	for rows.Next() {
		var i SkOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.ActivityNo,
			&i.SkuNo,
			&i.Quantity,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.PayAmount,
			&i.OrderStatus,
			&i.PaidAt,
			&i.ClosedAt,
			&i.TransactionNo,
			&i.TraceID,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, order_no, user_id, activity_no, sku_no, quantity, total_amount, discount_amount, pay_amount, order_status, paid_at, closed_at, transaction_no, trace_id, remark, created_at, updated_at, is_deleted FROM sk_order
WHERE user_id = $1 AND is_deleted = 0
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]SkOrder, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SkOrder{}
	for rows.Next() {
		var i SkOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.ActivityNo,
			&i.SkuNo,
			&i.Quantity,
			&i.TotalAmount,
			&i.DiscountAmount,
			&i.PayAmount,
			&i.OrderStatus,
			&i.PaidAt,
			&i.ClosedAt,
			&i.TransactionNo,
			&i.TraceID,
			&i.Remark,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderPaid = `-- name: MarkOrderPaid :exec
UPDATE sk_order
SET order_status = 'PAID',
    transaction_no = $2,
    paid_at = NOW(),
    updated_at = NOW()
WHERE order_no = $1 AND order_status = 'PENDING_PAY' AND is_deleted = 0
`

type MarkOrderPaidParams struct {
	OrderNo       string      `json:"order_no"`
	TransactionNo pgtype.Text `json:"transaction_no"`
}

func (q *Queries) MarkOrderPaid(ctx context.Context, arg MarkOrderPaidParams) error {
	_, err := q.db.Exec(ctx, markOrderPaid, arg.OrderNo, arg.TransactionNo)
	return err
}

const softDeleteOrder = `-- name: SoftDeleteOrder :exec
UPDATE sk_order
SET is_deleted = 1, updated_at = NOW()
WHERE order_no = $1
`

func (q *Queries) SoftDeleteOrder(ctx context.Context, orderNo string) error {
	_, err := q.db.Exec(ctx, softDeleteOrder, orderNo)
	return err
}
