// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/payment/v1/payment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	v1 "seckill-api/order/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PayAmount     int64                  `protobuf:"varint,3,opt,name=pay_amount,json=payAmount,proto3" json:"pay_amount,omitempty"`
	PayChannel    string                 `protobuf:"bytes,4,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	ExpireAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePay) Reset() {
	*x = CreatePay{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePay) ProtoMessage() {}

func (x *CreatePay) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePay.ProtoReflect.Descriptor instead.
func (*CreatePay) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePay) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreatePay) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePay) GetPayAmount() int64 {
	if x != nil {
		return x.PayAmount
	}
	return 0
}

func (x *CreatePay) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *CreatePay) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreatePay) GetExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpireAt
	}
	return nil
}

type PayResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayChannel    string                 `protobuf:"bytes,2,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	PrepayId      string                 `protobuf:"bytes,3,opt,name=prepay_id,json=prepayId,proto3" json:"prepay_id,omitempty"`
	NonceStr      string                 `protobuf:"bytes,4,opt,name=nonce_str,json=nonceStr,proto3" json:"nonce_str,omitempty"`
	TimeStamp     string                 `protobuf:"bytes,5,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Sign          string                 `protobuf:"bytes,6,opt,name=sign,proto3" json:"sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResult) Reset() {
	*x = PayResult{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResult) ProtoMessage() {}

func (x *PayResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResult.ProtoReflect.Descriptor instead.
func (*PayResult) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PayResult) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayResult) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

func (x *PayResult) GetPrepayId() string {
	if x != nil {
		return x.PrepayId
	}
	return ""
}

func (x *PayResult) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

func (x *PayResult) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *PayResult) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type PayQueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayStatus     int64                  `protobuf:"varint,2,opt,name=pay_status,json=payStatus,proto3" json:"pay_status,omitempty"`
	TransactionNo string                 `protobuf:"bytes,3,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	PaidAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayQueryResult) Reset() {
	*x = PayQueryResult{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayQueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayQueryResult) ProtoMessage() {}

func (x *PayQueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayQueryResult.ProtoReflect.Descriptor instead.
func (*PayQueryResult) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PayQueryResult) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PayQueryResult) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *PayQueryResult) GetTransactionNo() string {
	if x != nil {
		return x.TransactionNo
	}
	return ""
}

func (x *PayQueryResult) GetPaidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *CreatePay             `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentRequest) GetRequest() *CreatePay {
	if x != nil {
		return x.Request
	}
	return nil
}

type PrepayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	PayChannel    string                 `protobuf:"bytes,3,opt,name=pay_channel,json=payChannel,proto3" json:"pay_channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepayRequest) Reset() {
	*x = PrepayRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepayRequest) ProtoMessage() {}

func (x *PrepayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepayRequest.ProtoReflect.Descriptor instead.
func (*PrepayRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PrepayRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PrepayRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PrepayRequest) GetPayChannel() string {
	if x != nil {
		return x.PayChannel
	}
	return ""
}

type PaymentNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TransactionNo string                 `protobuf:"bytes,3,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentNotifyRequest) Reset() {
	*x = PaymentNotifyRequest{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentNotifyRequest) ProtoMessage() {}

func (x *PaymentNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentNotifyRequest.ProtoReflect.Descriptor instead.
func (*PaymentNotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentNotifyRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentNotifyRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PaymentNotifyRequest) GetTransactionNo() string {
	if x != nil {
		return x.TransactionNo
	}
	return ""
}

func (x *PaymentNotifyRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type PayResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PayResult             `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResultResponse) Reset() {
	*x = PayResultResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResultResponse) ProtoMessage() {}

func (x *PayResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResultResponse.ProtoReflect.Descriptor instead.
func (*PayResultResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PayResultResponse) GetResult() *PayResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type PayQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *PayQueryResult        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayQueryResponse) Reset() {
	*x = PayQueryResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayQueryResponse) ProtoMessage() {}

func (x *PayQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayQueryResponse.ProtoReflect.Descriptor instead.
func (*PayQueryResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PayQueryResponse) GetResult() *PayQueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type PayQueryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PayQueryResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayQueryListResponse) Reset() {
	*x = PayQueryListResponse{}
	mi := &file_api_payment_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayQueryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayQueryListResponse) ProtoMessage() {}

func (x *PayQueryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayQueryListResponse.ProtoReflect.Descriptor instead.
func (*PayQueryListResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *PayQueryListResponse) GetResults() []*PayQueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_payment_v1_payment_proto protoreflect.FileDescriptor

const file_api_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1capi/payment/v1/payment.proto\x12\x13seckill.api.payment\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18api/order/v1/order.proto\"\xd2\x01\n" +
	"\tCreatePay\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"pay_amount\x18\x03 \x01(\x03R\tpayAmount\x12\x1f\n" +
	"\vpay_channel\x18\x04 \x01(\tR\n" +
	"payChannel\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x127\n" +
	"\texpire_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bexpireAt\"\xb4\x01\n" +
	"\tPayResult\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vpay_channel\x18\x02 \x01(\tR\n" +
	"payChannel\x12\x1b\n" +
	"\tprepay_id\x18\x03 \x01(\tR\bprepayId\x12\x1b\n" +
	"\tnonce_str\x18\x04 \x01(\tR\bnonceStr\x12\x1d\n" +
	"\n" +
	"time_stamp\x18\x05 \x01(\tR\ttimeStamp\x12\x12\n" +
	"\x04sign\x18\x06 \x01(\tR\x04sign\"\xa6\x01\n" +
	"\x0ePayQueryResult\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"pay_status\x18\x02 \x01(\x03R\tpayStatus\x12%\n" +
	"\x0etransaction_no\x18\x03 \x01(\tR\rtransactionNo\x123\n" +
	"\apaid_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\"P\n" +
	"\x14CreatePaymentRequest\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1e.seckill.api.payment.CreatePayR\arequest\"d\n" +
	"\rPrepayRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vpay_channel\x18\x03 \x01(\tR\n" +
	"payChannel\"\xfc\x01\n" +
	"\x14PaymentNotifyRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12%\n" +
	"\x0etransaction_no\x18\x03 \x01(\tR\rtransactionNo\x12M\n" +
	"\x06params\x18\x04 \x03(\v25.seckill.api.payment.PaymentNotifyRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x11PayResultResponse\x126\n" +
	"\x06result\x18\x01 \x01(\v2\x1e.seckill.api.payment.PayResultR\x06result\"O\n" +
	"\x10PayQueryResponse\x12;\n" +
	"\x06result\x18\x01 \x01(\v2#.seckill.api.payment.PayQueryResultR\x06result\"U\n" +
	"\x14PayQueryListResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.seckill.api.payment.PayQueryResultR\aresults2\xa3\x04\n" +
	"\x0ePaymentService\x12T\n" +
	"\x06Prepay\x12\".seckill.api.payment.PrepayRequest\x1a&.seckill.api.payment.PayResultResponse\x12R\n" +
	"\rNotifyPayment\x12).seckill.api.payment.PaymentNotifyRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\rCreatePayment\x12).seckill.api.payment.CreatePaymentRequest\x1a&.seckill.api.payment.PayResultResponse\x12X\n" +
	"\fQueryPayment\x12!.seckill.api.order.OrderNoRequest\x1a%.seckill.api.payment.PayQueryResponse\x12^\n" +
	"\rQueryPayments\x12\".seckill.api.order.OrderNosRequest\x1a).seckill.api.payment.PayQueryListResponse\x12I\n" +
	"\fClosePayment\x12!.seckill.api.order.OrderNoRequest\x1a\x16.google.protobuf.EmptyB\x1bZ\x19seckill-api/payment/v1;v1b\x06proto3"

var (
	file_api_payment_v1_payment_proto_rawDescOnce sync.Once
	file_api_payment_v1_payment_proto_rawDescData []byte
)

func file_api_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_api_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_api_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)))
	})
	return file_api_payment_v1_payment_proto_rawDescData
}

var file_api_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_payment_v1_payment_proto_goTypes = []any{
	(*CreatePay)(nil),             // 0: seckill.api.payment.CreatePay
	(*PayResult)(nil),             // 1: seckill.api.payment.PayResult
	(*PayQueryResult)(nil),        // 2: seckill.api.payment.PayQueryResult
	(*CreatePaymentRequest)(nil),  // 3: seckill.api.payment.CreatePaymentRequest
	(*PrepayRequest)(nil),         // 4: seckill.api.payment.PrepayRequest
	(*PaymentNotifyRequest)(nil),  // 5: seckill.api.payment.PaymentNotifyRequest
	(*PayResultResponse)(nil),     // 6: seckill.api.payment.PayResultResponse
	(*PayQueryResponse)(nil),      // 7: seckill.api.payment.PayQueryResponse
	(*PayQueryListResponse)(nil),  // 8: seckill.api.payment.PayQueryListResponse
	nil,                           // 9: seckill.api.payment.PaymentNotifyRequest.ParamsEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*v1.OrderNoRequest)(nil),     // 11: seckill.api.order.OrderNoRequest
	(*v1.OrderNosRequest)(nil),    // 12: seckill.api.order.OrderNosRequest
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_api_payment_v1_payment_proto_depIdxs = []int32{
	10, // 0: seckill.api.payment.CreatePay.expire_at:type_name -> google.protobuf.Timestamp
	10, // 1: seckill.api.payment.PayQueryResult.paid_at:type_name -> google.protobuf.Timestamp
	0,  // 2: seckill.api.payment.CreatePaymentRequest.request:type_name -> seckill.api.payment.CreatePay
	9,  // 3: seckill.api.payment.PaymentNotifyRequest.params:type_name -> seckill.api.payment.PaymentNotifyRequest.ParamsEntry
	1,  // 4: seckill.api.payment.PayResultResponse.result:type_name -> seckill.api.payment.PayResult
	2,  // 5: seckill.api.payment.PayQueryResponse.result:type_name -> seckill.api.payment.PayQueryResult
	2,  // 6: seckill.api.payment.PayQueryListResponse.results:type_name -> seckill.api.payment.PayQueryResult
	4,  // 7: seckill.api.payment.PaymentService.Prepay:input_type -> seckill.api.payment.PrepayRequest
	5,  // 8: seckill.api.payment.PaymentService.NotifyPayment:input_type -> seckill.api.payment.PaymentNotifyRequest
	3,  // 9: seckill.api.payment.PaymentService.CreatePayment:input_type -> seckill.api.payment.CreatePaymentRequest
	11, // 10: seckill.api.payment.PaymentService.QueryPayment:input_type -> seckill.api.order.OrderNoRequest
	12, // 11: seckill.api.payment.PaymentService.QueryPayments:input_type -> seckill.api.order.OrderNosRequest
	11, // 12: seckill.api.payment.PaymentService.ClosePayment:input_type -> seckill.api.order.OrderNoRequest
	6,  // 13: seckill.api.payment.PaymentService.Prepay:output_type -> seckill.api.payment.PayResultResponse
	13, // 14: seckill.api.payment.PaymentService.NotifyPayment:output_type -> google.protobuf.Empty
	6,  // 15: seckill.api.payment.PaymentService.CreatePayment:output_type -> seckill.api.payment.PayResultResponse
	7,  // 16: seckill.api.payment.PaymentService.QueryPayment:output_type -> seckill.api.payment.PayQueryResponse
	8,  // 17: seckill.api.payment.PaymentService.QueryPayments:output_type -> seckill.api.payment.PayQueryListResponse
	13, // 18: seckill.api.payment.PaymentService.ClosePayment:output_type -> google.protobuf.Empty
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_payment_v1_payment_proto_init() }
func file_api_payment_v1_payment_proto_init() {
	if File_api_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_v1_payment_proto_rawDesc), len(file_api_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_api_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_api_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_api_payment_v1_payment_proto = out.File
	file_api_payment_v1_payment_proto_goTypes = nil
	file_api_payment_v1_payment_proto_depIdxs = nil
}
