// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/payment/v1/payment.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	v1 "seckill-api/order/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_Prepay_FullMethodName        = "/seckill.api.payment.PaymentService/Prepay"
	PaymentService_NotifyPayment_FullMethodName = "/seckill.api.payment.PaymentService/NotifyPayment"
	PaymentService_CreatePayment_FullMethodName = "/seckill.api.payment.PaymentService/CreatePayment"
	PaymentService_QueryPayment_FullMethodName  = "/seckill.api.payment.PaymentService/QueryPayment"
	PaymentService_QueryPayments_FullMethodName = "/seckill.api.payment.PaymentService/QueryPayments"
	PaymentService_ClosePayment_FullMethodName  = "/seckill.api.payment.PaymentService/ClosePayment"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	Prepay(ctx context.Context, in *PrepayRequest, opts ...grpc.CallOption) (*PayResultResponse, error)
	NotifyPayment(ctx context.Context, in *PaymentNotifyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*PayResultResponse, error)
	QueryPayment(ctx context.Context, in *v1.OrderNoRequest, opts ...grpc.CallOption) (*PayQueryResponse, error)
	QueryPayments(ctx context.Context, in *v1.OrderNosRequest, opts ...grpc.CallOption) (*PayQueryListResponse, error)
	ClosePayment(ctx context.Context, in *v1.OrderNoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) Prepay(ctx context.Context, in *PrepayRequest, opts ...grpc.CallOption) (*PayResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayResultResponse)
	err := c.cc.Invoke(ctx, PaymentService_Prepay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) NotifyPayment(ctx context.Context, in *PaymentNotifyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaymentService_NotifyPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*PayResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayResultResponse)
	err := c.cc.Invoke(ctx, PaymentService_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) QueryPayment(ctx context.Context, in *v1.OrderNoRequest, opts ...grpc.CallOption) (*PayQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayQueryResponse)
	err := c.cc.Invoke(ctx, PaymentService_QueryPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) QueryPayments(ctx context.Context, in *v1.OrderNosRequest, opts ...grpc.CallOption) (*PayQueryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayQueryListResponse)
	err := c.cc.Invoke(ctx, PaymentService_QueryPayments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ClosePayment(ctx context.Context, in *v1.OrderNoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PaymentService_ClosePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	Prepay(context.Context, *PrepayRequest) (*PayResultResponse, error)
	NotifyPayment(context.Context, *PaymentNotifyRequest) (*emptypb.Empty, error)
	CreatePayment(context.Context, *CreatePaymentRequest) (*PayResultResponse, error)
	QueryPayment(context.Context, *v1.OrderNoRequest) (*PayQueryResponse, error)
	QueryPayments(context.Context, *v1.OrderNosRequest) (*PayQueryListResponse, error)
	ClosePayment(context.Context, *v1.OrderNoRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) Prepay(context.Context, *PrepayRequest) (*PayResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Prepay not implemented")
}
func (UnimplementedPaymentServiceServer) NotifyPayment(context.Context, *PaymentNotifyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPayment not implemented")
}
func (UnimplementedPaymentServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*PayResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedPaymentServiceServer) QueryPayment(context.Context, *v1.OrderNoRequest) (*PayQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryPayment not implemented")
}
func (UnimplementedPaymentServiceServer) QueryPayments(context.Context, *v1.OrderNosRequest) (*PayQueryListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryPayments not implemented")
}
func (UnimplementedPaymentServiceServer) ClosePayment(context.Context, *v1.OrderNoRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePayment not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_Prepay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).Prepay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_Prepay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).Prepay(ctx, req.(*PrepayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_NotifyPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).NotifyPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_NotifyPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).NotifyPayment(ctx, req.(*PaymentNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_QueryPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.OrderNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).QueryPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_QueryPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).QueryPayment(ctx, req.(*v1.OrderNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_QueryPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.OrderNosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).QueryPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_QueryPayments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).QueryPayments(ctx, req.(*v1.OrderNosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ClosePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.OrderNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ClosePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ClosePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ClosePayment(ctx, req.(*v1.OrderNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.api.payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prepay",
			Handler:    _PaymentService_Prepay_Handler,
		},
		{
			MethodName: "NotifyPayment",
			Handler:    _PaymentService_NotifyPayment_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _PaymentService_CreatePayment_Handler,
		},
		{
			MethodName: "QueryPayment",
			Handler:    _PaymentService_QueryPayment_Handler,
		},
		{
			MethodName: "QueryPayments",
			Handler:    _PaymentService_QueryPayments_Handler,
		},
		{
			MethodName: "ClosePayment",
			Handler:    _PaymentService_ClosePayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/payment/v1/payment.proto",
}
