// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/activity/v1/activity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Status        int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	PurchaseLimit int64                  `protobuf:"varint,6,opt,name=purchase_limit,json=purchaseLimit,proto3" json:"purchase_limit,omitempty"`
	Remark        string                 `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Skus          []*SKU                 `protobuf:"bytes,8,rep,name=skus,proto3" json:"skus,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{0}
}

func (x *Activity) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Activity) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Activity) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Activity) GetPurchaseLimit() int64 {
	if x != nil {
		return x.PurchaseLimit
	}
	return 0
}

func (x *Activity) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Activity) GetSkus() []*SKU {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *Activity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Activity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SKU struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo      string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	SkuNo           string                 `protobuf:"bytes,2,opt,name=sku_no,json=skuNo,proto3" json:"sku_no,omitempty"`
	ProductName     string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ProductImage    string                 `protobuf:"bytes,4,opt,name=product_image,json=productImage,proto3" json:"product_image,omitempty"`
	OriginalPrice   int64                  `protobuf:"varint,5,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	SeckillPrice    int64                  `protobuf:"varint,6,opt,name=seckill_price,json=seckillPrice,proto3" json:"seckill_price,omitempty"`
	TotalStock      int64                  `protobuf:"varint,7,opt,name=total_stock,json=totalStock,proto3" json:"total_stock,omitempty"`
	LimitQuantity   int64                  `protobuf:"varint,8,opt,name=limit_quantity,json=limitQuantity,proto3" json:"limit_quantity,omitempty"`
	DiscountType    int64                  `protobuf:"varint,9,opt,name=discount_type,json=discountType,proto3" json:"discount_type,omitempty"`
	DiscountPrice   int64                  `protobuf:"varint,10,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	DiscountPercent int64                  `protobuf:"varint,11,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SKU) Reset() {
	*x = SKU{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKU) ProtoMessage() {}

func (x *SKU) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKU.ProtoReflect.Descriptor instead.
func (*SKU) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{1}
}

func (x *SKU) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *SKU) GetSkuNo() string {
	if x != nil {
		return x.SkuNo
	}
	return ""
}

func (x *SKU) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *SKU) GetProductImage() string {
	if x != nil {
		return x.ProductImage
	}
	return ""
}

func (x *SKU) GetOriginalPrice() int64 {
	if x != nil {
		return x.OriginalPrice
	}
	return 0
}

func (x *SKU) GetSeckillPrice() int64 {
	if x != nil {
		return x.SeckillPrice
	}
	return 0
}

func (x *SKU) GetTotalStock() int64 {
	if x != nil {
		return x.TotalStock
	}
	return 0
}

func (x *SKU) GetLimitQuantity() int64 {
	if x != nil {
		return x.LimitQuantity
	}
	return 0
}

func (x *SKU) GetDiscountType() int64 {
	if x != nil {
		return x.DiscountType
	}
	return 0
}

func (x *SKU) GetDiscountPrice() int64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *SKU) GetDiscountPercent() int64 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

type ActivityNoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityNoRequest) Reset() {
	*x = ActivityNoRequest{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityNoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityNoRequest) ProtoMessage() {}

func (x *ActivityNoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityNoRequest.ProtoReflect.Descriptor instead.
func (*ActivityNoRequest) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{2}
}

func (x *ActivityNoRequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

type SKURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	SkuNo         string                 `protobuf:"bytes,2,opt,name=sku_no,json=skuNo,proto3" json:"sku_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKURequest) Reset() {
	*x = SKURequest{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKURequest) ProtoMessage() {}

func (x *SKURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKURequest.ProtoReflect.Descriptor instead.
func (*SKURequest) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{3}
}

func (x *SKURequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *SKURequest) GetSkuNo() string {
	if x != nil {
		return x.SkuNo
	}
	return ""
}

type ActivityListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*Activity            `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityListResponse) Reset() {
	*x = ActivityListResponse{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityListResponse) ProtoMessage() {}

func (x *ActivityListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityListResponse.ProtoReflect.Descriptor instead.
func (*ActivityListResponse) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{4}
}

func (x *ActivityListResponse) GetActivities() []*Activity {
	if x != nil {
		return x.Activities
	}
	return nil
}

type ActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      *Activity              `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityResponse) Reset() {
	*x = ActivityResponse{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResponse) ProtoMessage() {}

func (x *ActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResponse.ProtoReflect.Descriptor instead.
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{5}
}

func (x *ActivityResponse) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type ActivityStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityStatusRequest) Reset() {
	*x = ActivityStatusRequest{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityStatusRequest) ProtoMessage() {}

func (x *ActivityStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityStatusRequest.ProtoReflect.Descriptor instead.
func (*ActivityStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{6}
}

func (x *ActivityStatusRequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *ActivityStatusRequest) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SKUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *SKU                   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKUResponse) Reset() {
	*x = SKUResponse{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKUResponse) ProtoMessage() {}

func (x *SKUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKUResponse.ProtoReflect.Descriptor instead.
func (*SKUResponse) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{7}
}

func (x *SKUResponse) GetSku() *SKU {
	if x != nil {
		return x.Sku
	}
	return nil
}

type ActivitySKURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityNo    string                 `protobuf:"bytes,1,opt,name=activity_no,json=activityNo,proto3" json:"activity_no,omitempty"`
	Sku           *SKU                   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivitySKURequest) Reset() {
	*x = ActivitySKURequest{}
	mi := &file_api_activity_v1_activity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivitySKURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitySKURequest) ProtoMessage() {}

func (x *ActivitySKURequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_activity_v1_activity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitySKURequest.ProtoReflect.Descriptor instead.
func (*ActivitySKURequest) Descriptor() ([]byte, []int) {
	return file_api_activity_v1_activity_proto_rawDescGZIP(), []int{8}
}

func (x *ActivitySKURequest) GetActivityNo() string {
	if x != nil {
		return x.ActivityNo
	}
	return ""
}

func (x *ActivitySKURequest) GetSku() *SKU {
	if x != nil {
		return x.Sku
	}
	return nil
}

var File_api_activity_v1_activity_proto protoreflect.FileDescriptor

const file_api_activity_v1_activity_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/activity/v1/activity.proto\x12\x14seckill.api.activity\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x03\n" +
	"\bActivity\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12%\n" +
	"\x0epurchase_limit\x18\x06 \x01(\x03R\rpurchaseLimit\x12\x16\n" +
	"\x06remark\x18\a \x01(\tR\x06remark\x12-\n" +
	"\x04skus\x18\b \x03(\v2\x19.seckill.api.activity.SKUR\x04skus\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x90\x03\n" +
	"\x03SKU\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x12\x15\n" +
	"\x06sku_no\x18\x02 \x01(\tR\x05skuNo\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12#\n" +
	"\rproduct_image\x18\x04 \x01(\tR\fproductImage\x12%\n" +
	"\x0eoriginal_price\x18\x05 \x01(\x03R\roriginalPrice\x12#\n" +
	"\rseckill_price\x18\x06 \x01(\x03R\fseckillPrice\x12\x1f\n" +
	"\vtotal_stock\x18\a \x01(\x03R\n" +
	"totalStock\x12%\n" +
	"\x0elimit_quantity\x18\b \x01(\x03R\rlimitQuantity\x12#\n" +
	"\rdiscount_type\x18\t \x01(\x03R\fdiscountType\x12%\n" +
	"\x0ediscount_price\x18\n" +
	" \x01(\x03R\rdiscountPrice\x12)\n" +
	"\x10discount_percent\x18\v \x01(\x03R\x0fdiscountPercent\"4\n" +
	"\x11ActivityNoRequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\"D\n" +
	"\n" +
	"SKURequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x12\x15\n" +
	"\x06sku_no\x18\x02 \x01(\tR\x05skuNo\"V\n" +
	"\x14ActivityListResponse\x12>\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1e.seckill.api.activity.ActivityR\n" +
	"activities\"N\n" +
	"\x10ActivityResponse\x12:\n" +
	"\bactivity\x18\x01 \x01(\v2\x1e.seckill.api.activity.ActivityR\bactivity\"P\n" +
	"\x15ActivityStatusRequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\":\n" +
	"\vSKUResponse\x12+\n" +
	"\x03sku\x18\x01 \x01(\v2\x19.seckill.api.activity.SKUR\x03sku\"b\n" +
	"\x12ActivitySKURequest\x12\x1f\n" +
	"\vactivity_no\x18\x01 \x01(\tR\n" +
	"activityNo\x12+\n" +
	"\x03sku\x18\x02 \x01(\v2\x19.seckill.api.activity.SKUR\x03sku2\xca\x05\n" +
	"\x0fActivityService\x12T\n" +
	"\x0eListActivities\x12\x16.google.protobuf.Empty\x1a*.seckill.api.activity.ActivityListResponse\x12^\n" +
	"\vGetActivity\x12'.seckill.api.activity.ActivityNoRequest\x1a&.seckill.api.activity.ActivityResponse\x12M\n" +
	"\x06GetSKU\x12 .seckill.api.activity.SKURequest\x1a!.seckill.api.activity.SKUResponse\x12`\n" +
	"\x0eCreateActivity\x12&.seckill.api.activity.ActivityResponse\x1a&.seckill.api.activity.ActivityResponse\x12P\n" +
	"\x0eUpdateActivity\x12&.seckill.api.activity.ActivityResponse\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x14UpdateActivityStatus\x12+.seckill.api.activity.ActivityStatusRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0eAddActivitySKU\x12(.seckill.api.activity.ActivitySKURequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x11RemoveActivitySKU\x12 .seckill.api.activity.SKURequest\x1a\x16.google.protobuf.EmptyB\x1cZ\x1aseckill-api/activity/v1;v1b\x06proto3"

var (
	file_api_activity_v1_activity_proto_rawDescOnce sync.Once
	file_api_activity_v1_activity_proto_rawDescData []byte
)

func file_api_activity_v1_activity_proto_rawDescGZIP() []byte {
	file_api_activity_v1_activity_proto_rawDescOnce.Do(func() {
		file_api_activity_v1_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_activity_v1_activity_proto_rawDesc), len(file_api_activity_v1_activity_proto_rawDesc)))
	})
	return file_api_activity_v1_activity_proto_rawDescData
}

var file_api_activity_v1_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_activity_v1_activity_proto_goTypes = []any{
	(*Activity)(nil),              // 0: seckill.api.activity.Activity
	(*SKU)(nil),                   // 1: seckill.api.activity.SKU
	(*ActivityNoRequest)(nil),     // 2: seckill.api.activity.ActivityNoRequest
	(*SKURequest)(nil),            // 3: seckill.api.activity.SKURequest
	(*ActivityListResponse)(nil),  // 4: seckill.api.activity.ActivityListResponse
	(*ActivityResponse)(nil),      // 5: seckill.api.activity.ActivityResponse
	(*ActivityStatusRequest)(nil), // 6: seckill.api.activity.ActivityStatusRequest
	(*SKUResponse)(nil),           // 7: seckill.api.activity.SKUResponse
	(*ActivitySKURequest)(nil),    // 8: seckill.api.activity.ActivitySKURequest
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_api_activity_v1_activity_proto_depIdxs = []int32{
	9,  // 0: seckill.api.activity.Activity.start_time:type_name -> google.protobuf.Timestamp
	9,  // 1: seckill.api.activity.Activity.end_time:type_name -> google.protobuf.Timestamp
	1,  // 2: seckill.api.activity.Activity.skus:type_name -> seckill.api.activity.SKU
	9,  // 3: seckill.api.activity.Activity.created_at:type_name -> google.protobuf.Timestamp
	9,  // 4: seckill.api.activity.Activity.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: seckill.api.activity.ActivityListResponse.activities:type_name -> seckill.api.activity.Activity
	0,  // 6: seckill.api.activity.ActivityResponse.activity:type_name -> seckill.api.activity.Activity
	1,  // 7: seckill.api.activity.SKUResponse.sku:type_name -> seckill.api.activity.SKU
	1,  // 8: seckill.api.activity.ActivitySKURequest.sku:type_name -> seckill.api.activity.SKU
	10, // 9: seckill.api.activity.ActivityService.ListActivities:input_type -> google.protobuf.Empty
	2,  // 10: seckill.api.activity.ActivityService.GetActivity:input_type -> seckill.api.activity.ActivityNoRequest
	3,  // 11: seckill.api.activity.ActivityService.GetSKU:input_type -> seckill.api.activity.SKURequest
	5,  // 12: seckill.api.activity.ActivityService.CreateActivity:input_type -> seckill.api.activity.ActivityResponse
	5,  // 13: seckill.api.activity.ActivityService.UpdateActivity:input_type -> seckill.api.activity.ActivityResponse
	6,  // 14: seckill.api.activity.ActivityService.UpdateActivityStatus:input_type -> seckill.api.activity.ActivityStatusRequest
	8,  // 15: seckill.api.activity.ActivityService.AddActivitySKU:input_type -> seckill.api.activity.ActivitySKURequest
	3,  // 16: seckill.api.activity.ActivityService.RemoveActivitySKU:input_type -> seckill.api.activity.SKURequest
	4,  // 17: seckill.api.activity.ActivityService.ListActivities:output_type -> seckill.api.activity.ActivityListResponse
	5,  // 18: seckill.api.activity.ActivityService.GetActivity:output_type -> seckill.api.activity.ActivityResponse
	7,  // 19: seckill.api.activity.ActivityService.GetSKU:output_type -> seckill.api.activity.SKUResponse
	5,  // 20: seckill.api.activity.ActivityService.CreateActivity:output_type -> seckill.api.activity.ActivityResponse
	10, // 21: seckill.api.activity.ActivityService.UpdateActivity:output_type -> google.protobuf.Empty
	10, // 22: seckill.api.activity.ActivityService.UpdateActivityStatus:output_type -> google.protobuf.Empty
	10, // 23: seckill.api.activity.ActivityService.AddActivitySKU:output_type -> google.protobuf.Empty
	10, // 24: seckill.api.activity.ActivityService.RemoveActivitySKU:output_type -> google.protobuf.Empty
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_activity_v1_activity_proto_init() }
func file_api_activity_v1_activity_proto_init() {
	if File_api_activity_v1_activity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_activity_v1_activity_proto_rawDesc), len(file_api_activity_v1_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_activity_v1_activity_proto_goTypes,
		DependencyIndexes: file_api_activity_v1_activity_proto_depIdxs,
		MessageInfos:      file_api_activity_v1_activity_proto_msgTypes,
	}.Build()
	File_api_activity_v1_activity_proto = out.File
	file_api_activity_v1_activity_proto_goTypes = nil
	file_api_activity_v1_activity_proto_depIdxs = nil
}
