// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/activity/v1/activity.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActivityService_ListActivities_FullMethodName       = "/seckill.api.activity.ActivityService/ListActivities"
	ActivityService_GetActivity_FullMethodName          = "/seckill.api.activity.ActivityService/GetActivity"
	ActivityService_GetSKU_FullMethodName               = "/seckill.api.activity.ActivityService/GetSKU"
	ActivityService_CreateActivity_FullMethodName       = "/seckill.api.activity.ActivityService/CreateActivity"
	ActivityService_UpdateActivity_FullMethodName       = "/seckill.api.activity.ActivityService/UpdateActivity"
	ActivityService_UpdateActivityStatus_FullMethodName = "/seckill.api.activity.ActivityService/UpdateActivityStatus"
	ActivityService_AddActivitySKU_FullMethodName       = "/seckill.api.activity.ActivityService/AddActivitySKU"
	ActivityService_RemoveActivitySKU_FullMethodName    = "/seckill.api.activity.ActivityService/RemoveActivitySKU"
)

// ActivityServiceClient is the client API for ActivityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityServiceClient interface {
	ListActivities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ActivityListResponse, error)
	GetActivity(ctx context.Context, in *ActivityNoRequest, opts ...grpc.CallOption) (*ActivityResponse, error)
	GetSKU(ctx context.Context, in *SKURequest, opts ...grpc.CallOption) (*SKUResponse, error)
	CreateActivity(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*ActivityResponse, error)
	UpdateActivity(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateActivityStatus(ctx context.Context, in *ActivityStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddActivitySKU(ctx context.Context, in *ActivitySKURequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveActivitySKU(ctx context.Context, in *SKURequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type activityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityServiceClient(cc grpc.ClientConnInterface) ActivityServiceClient {
	return &activityServiceClient{cc}
}

func (c *activityServiceClient) ListActivities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ActivityListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityListResponse)
	err := c.cc.Invoke(ctx, ActivityService_ListActivities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) GetActivity(ctx context.Context, in *ActivityNoRequest, opts ...grpc.CallOption) (*ActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityResponse)
	err := c.cc.Invoke(ctx, ActivityService_GetActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) GetSKU(ctx context.Context, in *SKURequest, opts ...grpc.CallOption) (*SKUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SKUResponse)
	err := c.cc.Invoke(ctx, ActivityService_GetSKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) CreateActivity(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*ActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivityResponse)
	err := c.cc.Invoke(ctx, ActivityService_CreateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) UpdateActivity(ctx context.Context, in *ActivityResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ActivityService_UpdateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) UpdateActivityStatus(ctx context.Context, in *ActivityStatusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ActivityService_UpdateActivityStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) AddActivitySKU(ctx context.Context, in *ActivitySKURequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ActivityService_AddActivitySKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityServiceClient) RemoveActivitySKU(ctx context.Context, in *SKURequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ActivityService_RemoveActivitySKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServiceServer is the server API for ActivityService service.
// All implementations must embed UnimplementedActivityServiceServer
// for forward compatibility.
type ActivityServiceServer interface {
	ListActivities(context.Context, *emptypb.Empty) (*ActivityListResponse, error)
	GetActivity(context.Context, *ActivityNoRequest) (*ActivityResponse, error)
	GetSKU(context.Context, *SKURequest) (*SKUResponse, error)
	CreateActivity(context.Context, *ActivityResponse) (*ActivityResponse, error)
	UpdateActivity(context.Context, *ActivityResponse) (*emptypb.Empty, error)
	UpdateActivityStatus(context.Context, *ActivityStatusRequest) (*emptypb.Empty, error)
	AddActivitySKU(context.Context, *ActivitySKURequest) (*emptypb.Empty, error)
	RemoveActivitySKU(context.Context, *SKURequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedActivityServiceServer()
}

// UnimplementedActivityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityServiceServer struct{}

func (UnimplementedActivityServiceServer) ListActivities(context.Context, *emptypb.Empty) (*ActivityListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActivities not implemented")
}
func (UnimplementedActivityServiceServer) GetActivity(context.Context, *ActivityNoRequest) (*ActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedActivityServiceServer) GetSKU(context.Context, *SKURequest) (*SKUResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSKU not implemented")
}
func (UnimplementedActivityServiceServer) CreateActivity(context.Context, *ActivityResponse) (*ActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedActivityServiceServer) UpdateActivity(context.Context, *ActivityResponse) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateActivity not implemented")
}
func (UnimplementedActivityServiceServer) UpdateActivityStatus(context.Context, *ActivityStatusRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateActivityStatus not implemented")
}
func (UnimplementedActivityServiceServer) AddActivitySKU(context.Context, *ActivitySKURequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddActivitySKU not implemented")
}
func (UnimplementedActivityServiceServer) RemoveActivitySKU(context.Context, *SKURequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveActivitySKU not implemented")
}
func (UnimplementedActivityServiceServer) mustEmbedUnimplementedActivityServiceServer() {}
func (UnimplementedActivityServiceServer) testEmbeddedByValue()                         {}

// UnsafeActivityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityServiceServer will
// result in compilation errors.
type UnsafeActivityServiceServer interface {
	mustEmbedUnimplementedActivityServiceServer()
}

func RegisterActivityServiceServer(s grpc.ServiceRegistrar, srv ActivityServiceServer) {
	// If the following call panics, it indicates UnimplementedActivityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActivityService_ServiceDesc, srv)
}

func _ActivityService_ListActivities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).ListActivities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityService_ListActivities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).ListActivities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityService_GetActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).GetActivity(ctx, req.(*ActivityNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_GetSKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).GetSKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityService_GetSKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).GetSKU(ctx, req.(*SKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityService_CreateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).CreateActivity(ctx, req.(*ActivityResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_UpdateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).UpdateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityService_UpdateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).UpdateActivity(ctx, req.(*ActivityResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_UpdateActivityStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivityStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).UpdateActivityStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityService_UpdateActivityStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).UpdateActivityStatus(ctx, req.(*ActivityStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_AddActivitySKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivitySKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).AddActivitySKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityService_AddActivitySKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).AddActivitySKU(ctx, req.(*ActivitySKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActivityService_RemoveActivitySKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServiceServer).RemoveActivitySKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActivityService_RemoveActivitySKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServiceServer).RemoveActivitySKU(ctx, req.(*SKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActivityService_ServiceDesc is the grpc.ServiceDesc for ActivityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActivityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "seckill.api.activity.ActivityService",
	HandlerType: (*ActivityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListActivities",
			Handler:    _ActivityService_ListActivities_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _ActivityService_GetActivity_Handler,
		},
		{
			MethodName: "GetSKU",
			Handler:    _ActivityService_GetSKU_Handler,
		},
		{
			MethodName: "CreateActivity",
			Handler:    _ActivityService_CreateActivity_Handler,
		},
		{
			MethodName: "UpdateActivity",
			Handler:    _ActivityService_UpdateActivity_Handler,
		},
		{
			MethodName: "UpdateActivityStatus",
			Handler:    _ActivityService_UpdateActivityStatus_Handler,
		},
		{
			MethodName: "AddActivitySKU",
			Handler:    _ActivityService_AddActivitySKU_Handler,
		},
		{
			MethodName: "RemoveActivitySKU",
			Handler:    _ActivityService_RemoveActivitySKU_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/activity/v1/activity.proto",
}
