// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/member/v1/member.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	v1 "seckill-api/common/v1"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	MemberLevel   int64                  `protobuf:"varint,6,opt,name=member_level,json=memberLevel,proto3" json:"member_level,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_member_v1_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_member_v1_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_member_v1_member_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetMemberLevel() int64 {
	if x != nil {
		return x.MemberLevel
	}
	return 0
}

func (x *User) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneRequest) Reset() {
	*x = PhoneRequest{}
	mi := &file_api_member_v1_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneRequest) ProtoMessage() {}

func (x *PhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_member_v1_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneRequest.ProtoReflect.Descriptor instead.
func (*PhoneRequest) Descriptor() ([]byte, []int) {
	return file_api_member_v1_member_proto_rawDescGZIP(), []int{1}
}

func (x *PhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_api_member_v1_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_member_v1_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_api_member_v1_member_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type MemberLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberLevel   int64                  `protobuf:"varint,1,opt,name=member_level,json=memberLevel,proto3" json:"member_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberLevelResponse) Reset() {
	*x = MemberLevelResponse{}
	mi := &file_api_member_v1_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLevelResponse) ProtoMessage() {}

func (x *MemberLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_member_v1_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLevelResponse.ProtoReflect.Descriptor instead.
func (*MemberLevelResponse) Descriptor() ([]byte, []int) {
	return file_api_member_v1_member_proto_rawDescGZIP(), []int{3}
}

func (x *MemberLevelResponse) GetMemberLevel() int64 {
	if x != nil {
		return x.MemberLevel
	}
	return 0
}

var File_api_member_v1_member_proto protoreflect.FileDescriptor

const file_api_member_v1_member_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/member/v1/member.proto\x12\x12seckill.api.member\x1a\x1aapi/common/v1/common.proto\"\xb7\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\x12!\n" +
	"\fmember_level\x18\x06 \x01(\x03R\vmemberLevel\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\"$\n" +
	"\fPhoneRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"<\n" +
	"\fUserResponse\x12,\n" +
	"\x04user\x18\x01 \x01(\v2\x18.seckill.api.member.UserR\x04user\"8\n" +
	"\x13MemberLevelResponse\x12!\n" +
	"\fmember_level\x18\x01 \x01(\x03R\vmemberLevel2\x97\x02\n" +
	"\rMemberService\x12R\n" +
	"\vGetUserByID\x12!.seckill.api.common.UserIDRequest\x1a .seckill.api.member.UserResponse\x12T\n" +
	"\x0eGetUserByPhone\x12 .seckill.api.member.PhoneRequest\x1a .seckill.api.member.UserResponse\x12\\\n" +
	"\x0eGetMemberLevel\x12!.seckill.api.common.UserIDRequest\x1a'.seckill.api.member.MemberLevelResponseB\x1aZ\x18seckill-api/member/v1;v1b\x06proto3"

var (
	file_api_member_v1_member_proto_rawDescOnce sync.Once
	file_api_member_v1_member_proto_rawDescData []byte
)

func file_api_member_v1_member_proto_rawDescGZIP() []byte {
	file_api_member_v1_member_proto_rawDescOnce.Do(func() {
		file_api_member_v1_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_member_v1_member_proto_rawDesc), len(file_api_member_v1_member_proto_rawDesc)))
	})
	return file_api_member_v1_member_proto_rawDescData
}

var file_api_member_v1_member_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_member_v1_member_proto_goTypes = []any{
	(*User)(nil),                // 0: seckill.api.member.User
	(*PhoneRequest)(nil),        // 1: seckill.api.member.PhoneRequest
	(*UserResponse)(nil),        // 2: seckill.api.member.UserResponse
	(*MemberLevelResponse)(nil), // 3: seckill.api.member.MemberLevelResponse
	(*v1.UserIDRequest)(nil),    // 4: seckill.api.common.UserIDRequest
}
var file_api_member_v1_member_proto_depIdxs = []int32{
	0, // 0: seckill.api.member.UserResponse.user:type_name -> seckill.api.member.User
	4, // 1: seckill.api.member.MemberService.GetUserByID:input_type -> seckill.api.common.UserIDRequest
	1, // 2: seckill.api.member.MemberService.GetUserByPhone:input_type -> seckill.api.member.PhoneRequest
	4, // 3: seckill.api.member.MemberService.GetMemberLevel:input_type -> seckill.api.common.UserIDRequest
	2, // 4: seckill.api.member.MemberService.GetUserByID:output_type -> seckill.api.member.UserResponse
	2, // 5: seckill.api.member.MemberService.GetUserByPhone:output_type -> seckill.api.member.UserResponse
	3, // 6: seckill.api.member.MemberService.GetMemberLevel:output_type -> seckill.api.member.MemberLevelResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_member_v1_member_proto_init() }
func file_api_member_v1_member_proto_init() {
	if File_api_member_v1_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_member_v1_member_proto_rawDesc), len(file_api_member_v1_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_member_v1_member_proto_goTypes,
		DependencyIndexes: file_api_member_v1_member_proto_depIdxs,
		MessageInfos:      file_api_member_v1_member_proto_msgTypes,
	}.Build()
	File_api_member_v1_member_proto = out.File
	file_api_member_v1_member_proto_goTypes = nil
	file_api_member_v1_member_proto_depIdxs = nil
}
